### ISSUE TITLE
Multiple PopTips

### ISSUE THREAD

**Issue by docash59** [andreamazz/AMPopTip#1]
How do I show multiple popTips at the same time?

**Comment by acegreen** [comment]
I noticed to dismiss multiple popTips you would need to tap as many times as there are popTips? can't we dismiss all with one tap?

**Comment by andreamazz** [comment]
Each popTip with `dismissOnTapOutside` enabled will bind a new gesture recognizer, so only the last one will dismiss. If you want to dismiss all of them the best course of action would be to disable the `dismissOnTapOutside` property and implement your own tap gesture recognizer in the container view, that will do something like this:
```swift
 for (AMPopTip *tip in tips) {
        [tip hide];
    }
```

**Comment by acegreen** [comment]
Interesting, I think this should be an option to dismiss all poptips. How do I detect all popTips?

**Comment by andreamazz** [comment]
It's not the poptip's job to track other poptips, it would be like asking an UITextField to clear the text out of all the textfields in view. That's the view controller's job.  
If you have multiple poptips at the same time, store them in an array and call `hide` when appropriate.

**Comment by acegreen** [comment]
Fair enough. I'm looking to create a AMPopTipController where I can track all the popTips. Another question. Can we use a UIBarButtonItem as anchor? I can calculate the location of that item by myself but it differs on iPad vs iPhone so its not practical.

**Comment by acegreen** [comment]
Any way we can say instead of fromView, we do from anchor and just pass it the UIBarButtonItem? like a popOver segue would do

**Comment by andreamazz** [comment]
Getting the frame of a UIBarButtonItem is behind a private API, so I can't use it in a library as it might get people rejected.

**Comment by acegreen** [comment]
Yea I read about that. So the popover controller uses a private API when it sets its anchor? And what do users of this library do to make a popTip appear at UIBarButtonItem or UINavigationItem?

**Comment by andreamazz** [comment]
> Yea I read about that. So the popover controller uses a private API when it sets its anchor?

That would be my guess, since it's Apple's stuff anyway :)



> And what do users of this library do to make a popTip appear at UIBarButtonItem or UINavigationItem?

Personally I compute the starting point using the navbar height and the screen's width.

**Comment by acegreen** [comment]
I see

I did that but it differs on iPad vs iPhone? I would need to check device and compensate for it or?

**Comment by andreamazz** [comment]
Sadly, yes, until Apple provides a better way to to it, but I wouldn't hold my breath.

**Comment by acegreen** [comment]
Alright if you don't hear from me then you know I held my breath and died away.
