### ISSUE TITLE
AMPopTip flashes fullscreen if hideForced:YES called while still animating up.

### ISSUE THREAD

**Issue by eminallen** [andreamazz/AMPopTip#100]
I've noticed if I create a AMPopTip and then call hideForced:YES before it's finished animating, AMPopTip will scale up full screen for a frame (flash) before shrinking down.

Adding a [self.layer removeAllAnimations]; in hideForced: fixes the issue for me.

This might also fix #48 and #84.

**Comment by andreamazz** [comment]
Good catch, thanks @eminallen
