### ISSUE TITLE
Custom AMPopTip animation in Swift

### ISSUE THREAD

**Issue by faraz-hussain** [andreamazz/AMPopTip#103]
I'm sure I'm doing something extremely silly, but the following code in my viewDidLoad function throws an unresolved identifier issue at the last line:

        self.popTip = AMPopTip()
        self.popTip?.shouldDismissOnTap = true
        self.popTip?.edgeMargin = 5
        self.popTip?.offset = 200
        self.popTip?.edgeInsets = UIEdgeInsets(top: 0,left: 10,bottom: 0,right: 10)
        self.popTip?.popoverColor = self.view.tintColor
        self.popTip?.actionAnimation = AMPopTipActionAnimationBounce

error: Use of unresolved identifier 'AMPopTipActionAnimationBounce'

Whereas this doesn't work either:

        self.popTip = AMPopTip()
        self.popTip?.shouldDismissOnTap = true
        self.popTip?.edgeMargin = 5
        self.popTip?.offset = 200
        self.popTip?.edgeInsets = UIEdgeInsets(top: 0,left: 10,bottom: 0,right: 10)
        self.popTip?.popoverColor = self.view.tintColor
        self.popTip?.actionAnimation = AMPopTip.AMPopTipActionAnimationBounce

error: Type 'AMPopTip' has no member 'AMPopTipEntranceAnimationNone'

Without the animation, my PopTips works just fine. I set up using Carthage, added AMPopTip.framework to my target's linked frameworks and libraries and copied AMPopTip.h to my target's bundle resources.

[DashboardTableViewController.txt](https://github.com/andreamazz/AMPopTip/files/793678/DashboardTableViewController.txt)

**Comment by andreamazz** [comment]
```swift
self.popTip?.actionAnimation = .bounce
```

**Comment by faraz-hussain** [comment]
Thank you!
