### ISSUE TITLE
Animation stops when application enters background

### ISSUE THREAD

**Issue by lalania** [andreamazz/AMPopTip#106]
When an actionAnimation is applied to the tooltip and the application goes into the background (user clicks the Home button), the animation is paused when the application enters foreground. 

I tried listening for the UIApplicationDidBecomeActiveNotification notification and calling startActionAnimation when the app enters the foreground, but that didn't work.

**Comment by andreamazz** [comment]
Hey @lalania,
I've updated the sample project to include the resume after the background. I tried the approach you suggested, and it seems to be working:
```objc
[[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(resumeAnimation) name:UIApplicationDidBecomeActiveNotification object:nil];
```

```objc
- (void)resumeAnimation {
    [self.popTip stopActionAnimation];
    [self.popTip startActionAnimation];
}
```

Calling the stop action method ensures that the animation doesn't glitch out.
