### ISSUE TITLE
Popup does not display full text at the first time

### ISSUE THREAD

**Issue by purepure** [andreamazz/AMPopTip#108]
Hi!
This is wonderful lib. Thank you so much for this

When I integrate your lib into my project, at the first time showup the tip, it cannot show full of my text (long string). It only show the first line of my text, and does not span the popview to display all of them. After the first popup, it display normally.

Hope you can fix this issue soon
Thank

**Comment by andreamazz** [comment]
Hey @purepure 
Can you provide some sample code to reproduce the issue?

**Comment by purepure** [comment]
I setup Poptip like this in Appdelegate.m
AMPopTip *appearance = [AMPopTip appearance];
	[appearance setShouldDismissOnTapOutside:YES];
	[appearance setShouldDismissOnTap:YES];
	appearance.textColor = [UIColor whiteColor];
	appearance.padding = 10;
	appearance.edgeInsets = UIEdgeInsetsMake(5, 5, 5, 5);
	appearance.font = [UIFont boldSystemFontOfSize:15];
	appearance.textAlignment = NSTextAlignmentLeft;

And then in the MainViewController, I create the first poptip with long text 

poptip = [AMPopTip popTip]; //poptip is global variable
[tutview showText:@"Vuốt màn hình từ trái qua phải để mở danh mục kênh." direction:AMPopTipDirectionRight maxWidth:240 inView:root fromFrame:rect];

<img width="334" alt="screen shot 2017-03-24 at 00 35 10" src="https://cloud.githubusercontent.com/assets/3175469/24261515/cd880014-1029-11e7-8b96-2a7cb97d65dd.png">

The text is in VietNamese and cannot be displayed completely. After this one, the other display normally

**Comment by andreamazz** [comment]
Try to set the font on the instance of the poptip instead of the appearance proxy.

**Comment by andreamazz** [comment]
Note that the font is not a property that can be set via appearance:

![screen shot 2017-03-23 at 18 44 37](https://cloud.githubusercontent.com/assets/570797/24261911/d1daea22-0ff8-11e7-9052-28e48e1f65f0.png)

**Comment by purepure** [comment]
Oh, it works! Thank you so much. I did not figure out that the font is not proxy property. You save my day!

**Comment by andreamazz** [comment]
👍
