### ISSUE TITLE
XCode 8.3.1 warnings

### ISSUE THREAD

**Issue by ranhsd** [andreamazz/AMPopTip#110]
Hi , i get some warnings after upgrading my xcode to the latest release (8.3.1)

The warnings are: 

<img width="453" alt="screen shot 2017-04-12 at 14 50 05" src="https://cloud.githubusercontent.com/assets/3685671/24956230/69072000-1f8f-11e7-8e2e-fa3b9f534894.png">

Thanks!

**Comment by JamesKuang** [comment]
Here you go https://github.com/andreamazz/AMPopTip/pull/111

**Comment by andreamazz** [comment]
Released `1.5.1`

**Comment by ranhsd** [comment]
Thanks a lot !
