### ISSUE TITLE
PopUp show under other view

### ISSUE THREAD

**Issue by MervinFlores** [andreamazz/AMPopTip#113]
Hi!, the pop up show behind de next view, any solution?, thanks.

![screen shot 2017-04-17 at 11 29 04 am](https://cloud.githubusercontent.com/assets/25008671/25093636/18f970e2-2361-11e7-8479-988b2e8e47cc.png)

**Comment by andreamazz** [comment]
Hey @MervinFlores 
If my eyes don't deceive me, it's not behind, it's just empty

**Comment by MervinFlores** [comment]
@andreamazz its behind, if I remove the next view the text is show normally. the same in others views, the bubble text is cut for the middle or something like that.

**Comment by andreamazz** [comment]
@MervinFlores gotcha. Anyway, the poptip is added as a subview, so if there is an ordering issue there is not much that can be done beside calling bringSubviewToFront: (See [UIView's doc](https://developer.apple.com/reference/uikit/uiview/1622541-bringsubviewtofront))
