### ISSUE TITLE
`isVisible` returns always `true` when application enters background while a popup is presented

### ISSUE THREAD

**Issue by adamkovica** [andreamazz/AMPopTip#114]
When user enters background while a tooltip is presented and then comes back, tooltip is not presented anymore, but `isVisible` returns `true`

**Comment by andreamazz** [comment]
Hey @adamkovica 
Good catch, this should be fixed in the latest commit.

**Comment by adamkovica** [comment]
Hey @andreamazz thanks a lot for prompt reply!

I have checked out the latest version, but unfortunately there is still same issue. Attaching the console output after coming back from background state.

![screen shot 2017-05-02 at 3 31 41 pm](https://cloud.githubusercontent.com/assets/4047822/25635645/d5610578-2f4c-11e7-9a2e-802b5d72cd3d.png)

**Comment by andreamazz** [comment]
Hey @adamkovica, can you post the steps to reproduce the issue?

**Comment by adamkovica** [comment]
Sure:
1) `AMPopTip` is @property on `UITableViewCell`
2) Present `AMPopTip` by calling `showText:direction:maxWidth:inView:fromFrame:duration:` on the property while app is in foreground
3) While `AMPopTip` is till presented and animation did nit finish, put app to background by pressing a home button
4) Open the app again. `AMPopTip` is not visible, but when you check `isVisible` on the @property it returns `true`

**Comment by andreamazz** [comment]
Hey @adamkovica 
I tried to reproduce the issue, but with no luck, the poptip is there once I return from the background. 

Can you by any chance test on your setup the latest version? (`2.0.1`)

**Comment by andreamazz** [comment]
Hi @adamkovica 
Sorry for the delay. I was able to fix the issue in the latest version. The API changed a bit, but upgrading shouldn't be too time consuming. I'm having issues replicating the fix with Objective-C for some reason.
