### ISSUE TITLE
Swift version

### ISSUE THREAD

**Issue by andreamazz** [andreamazz/AMPopTip#115]
Hi everyone,
I've converted the library in Swift, and took the chance to clean up part of the API.  
Since part of the code was refactored, some manual tests for some edge cases would be welcomed 😬 

For now everything is in the `swift` branch, the current version will live under the `v1.x` branch.

**Comment by nevinjethmalani** [comment]
I am getting an issue with the arrow not being centered in the frame. It is slightly pushed to the left side of the frame that I am tapping. Here is the code I am using:

`self.popTip.show(text: theText, direction: .up, maxWidth: 250, in: self.mainView, from: (sender as AnyObject).frame)`

**Comment by andreamazz** [comment]
Hi @nevinjethmalani 
Yeah, I've noticed that this issue arise when you have a poptip with the bouncing animation and you dismiss it while it's bouncing down. When you reopen it, it's shifted. This can be observed in the demo project. 
I'll fix it as soon as possible.

**Comment by andreamazz** [comment]
Ok, the latest commit seems to have fixed this issue, let me know if you are still experiencing it

**Comment by nevinjethmalani** [comment]
I am still having the problem. Even if I don't dismiss it when it is bouncing, I have this issue.

**Comment by andreamazz** [comment]
Can you post more details to help me reproduce the issue? e.g.: some info on the view containing it and the frame originating it. 

Thanks

**Comment by Kaspik** [comment]
Would it be possible to make even this new swift version compatible with Obj-C apps? Like adding @objc in front of the class to make it obj-c public-visible?

**Comment by andreamazz** [comment]
Hey @Kaspik 
The swift version uses some swift-only constructs (mainly associated enum values) that are not available to Objective-C, so by design I decided to limit the compatibility from the start. The Objective-C version (branch `v1.x`) is stable though, and offers the same features, so you can point to that one instead.

**Comment by Kaspik** [comment]
@andreamazz Thanks for the response. Yeah we already use the older version, the question was more like if you already have half of the code with prefix @objc then if you are going to do it fully objc compatible or not.
That (one?) associated enum could be maybe represented by struct but i understand you.
It's not like we don't wanna use swift but our project is so huge that right now it's not possible to rewrite it as you did... and we don't wanna loose new functions of this library. 😔

Thanks anyways!

**Comment by vickydhas** [comment]
Can you give the pod link for the ObjC version please.

**Comment by vickydhas** [comment]
I managed :     pod 'AMPopTip' , '~>1.x'
