### ISSUE TITLE
PopTip's `containerView` incorrectly fires `tapHandler`

### ISSUE THREAD

**Issue by ronaldsmartin** [andreamazz/AMPopTip#116]
Hi, thanks for building this!

In the new Swift version of the pop tip, you're adding the gesture recognizer for `tapHandler` to the poptip's container view instead of to the pop tip itself ([line 511](https://github.com/andreamazz/AMPopTip/blob/master/Source/PopTip.swift#L511)). This results in the `tapHandler` getting fired when tapping outside the pop tip, which is a regression from the previous version.

You may need to have separate gesture recognizers for handling taps inside and outside the poptip. 😄

**Comment by andreamazz** [comment]
Hey @ronaldsmartin, nice catch! Thanks, should be fixed now.
