### ISSUE TITLE
Swift Compiler Warning

### ISSUE THREAD

**Issue by rogpfreck** [andreamazz/AMPopTip#118]
![ampoptip compiler warnings](https://cloud.githubusercontent.com/assets/13650919/26216047/9898f4ce-3bfa-11e7-9d81-3ded1e1296c9.png)

Just updated to latest ver. I get the above warnings. Otherwise all good.

**Comment by andreamazz** [comment]
Hi @rogpfreck 
this seems to be just the CocoaPods cache, try removing the Pods folder and launching `pod install` again

**Comment by rogpfreck** [comment]
Worked. Thanks!
