### ISSUE TITLE
Pulse animation stopped working in version 2

### ISSUE THREAD

**Issue by Ruyven** [andreamazz/AMPopTip#119]
The .pulse(CGFloat?) animation stopped working since I started using version 2; no matter what parameter I use, it only pulses once and then leaves the big version of the poptip hanging there.
For now I reverted to version 1.5.2, but I would prefer being able to use the Swift version.

**Comment by andreamazz** [comment]
Hey @Ruyven 
Should be fixed with the latest commit.
