### ISSUE TITLE
PopTip Over UITabBar

### ISSUE THREAD

**Issue by uuwen** [andreamazz/AMPopTip#122]
Hi, I am trying to make PopTip appear above the tab bar by using the following code. I set the tab bar as the target UIVIew and using the 3rd UITabBarItem's frame but nothing appears. It worked on a button but not this.

```swift
let tabBar = tabBarController!.tabBar
let width = tabBar.frame.size.width / CGFloat((tabBar.items?.count)!)
let height = tabBar.frame.size.height
let rect = CGRect(x: width * 2, y: 0, width: width, height: height)
         
popTip.show(text: "Make appointment", direction: .down, maxWidth: 200, in: tabBar, from: rect)
```

**Comment by andreamazz** [comment]
Hey @uuwen 
You are setting `down` as direction, the poptip is probably below the tabbar. Try up, or move up the frame.

**Comment by andreamazz** [comment]
Closing this. Feel free to reopen if needed.

**Comment by uuwen** [comment]
Thanks! I made the wrong assumption that this parameter is the same as `popoverPresentationController?.permittedArrowDirections`. Great library!
