### ISSUE TITLE
Taps is not forwarded to subviews due to `cancelsTouchesInView` property

### ISSUE THREAD

**Issue by vinayakparmar92** [andreamazz/AMPopTip#123]
https://github.com/andreamazz/AMPopTip/blob/36d3a2a524a8cb7e39be4497ec1ebe7fe08cd0c4/Source/PopTip.swift#L399

**Comment by andreamazz** [comment]
This is the intended behaviour, I can however add a property to enable or disable it, would that do?

**Comment by najmul-csebuet** [comment]
Yes, we need that property.

**Comment by najmul-csebuet** [comment]
`_popTip.appearHandler = { popTip in
            
            let gestureRecognizers = popTip.gestureRecognizers
            gestureRecognizers?.first?.cancelsTouchesInView = false
        }`

**Comment by andreamazz** [comment]
Checkout the latest commit. I've made the tap handler public, so you can set it as you will:
```swift
popTip.tapGestureRecognizer?.cancelsTouchesInView = false
```
