### ISSUE TITLE
Can't show PopTip

### ISSUE THREAD

**Issue by Recouse** [andreamazz/AMPopTip#127]
Can't show PopTip above text field. Here is my code:
```swift
let popTip = PopTip()
popTip.show(text: "15 USD", direction: .up, maxWidth: 200, in: view, from: textField.frame)
```

**Comment by andreamazz** [comment]
Hey @Recouse 
I tested the same code you posted and it's working fine:

<img width="346" alt="screen shot 2018-01-30 at 15 30 57" src="https://user-images.githubusercontent.com/570797/35571501-96b9007a-05d2-11e8-8efd-8641475944c8.png">
