### ISSUE TITLE
Breakpoint for Swift 4

### ISSUE THREAD

**Issue by ndduong97** [andreamazz/AMPopTip#128]
I'm running the latest version of AMPopTip on Xcode 9 but I am getting a thread 1: breakpoint 1.2 on this line

`  open var font = UIFont.systemFont(ofSize: UIFont.systemFontSize)`

There are no errors or warning, but when the app is run, it stops at this line and gives out the breakpoint warning. I am not sure what is happening here.

Edit: I figured it out that the exception breakpoint was giving me this error.

**Comment by andreamazz** [comment]
> Edit: I figured it out that the exception breakpoint was giving me this error.

So can I close this?  
In any case, I see no problems with the sample project, even with the exception breakpoint turned on, odd...

**Comment by ndduong97** [comment]
That is strange. It works if exception breakpoint is off but it stops when it is on. Do you think it can be the UI System Font?

**Comment by andreamazz** [comment]
Once it stops, you can just hit continue in the debug panel and it should work. Maybe you'll see more info on the exception in the console.
