### ISSUE TITLE
Did you drop iOS 9-10 support?

### ISSUE THREAD

**Issue by sample-repo** [andreamazz/AMPopTip#130]
I cannot build the last release using Xcode 8.3.3 (8E3004b). 
The error is  "Use of unresolved identifier 'NSAttributedStringKey'".
According to [documentation](https://developer.apple.com/documentation/foundation/nsattributedstringkey ) NSAttributedStringKey works under iOS 11.0+.

**Comment by andreamazz** [comment]
https://github.com/andreamazz/AMPopTip#versioning-notes

Use version 2.x

**Comment by sample-repo** [comment]
To be honest it is not good decision to support only latest version. And it is not user-friendly behaviour for devs who use your awesome library. 
Probably, you will introduce new features or fix some bugs in the future. As a result, the changes won't affect lower versions.

The golden rule defined on our project is "keep libraries up-to-date". For now I am thinking of alternative.

**Comment by andreamazz** [comment]
Swift 3 version is not deprecated, it just lives in the `swift3` branch.

**Comment by dirtmelon** [comment]
I do not think it's a good decision.If I want support iOS 9-10,I must use Swift 3,I can't use Swift 4,so sad.

**Comment by andreamazz** [comment]
@dirtmelon The library works with iOS9 and 10, you just need to compile with Xcode 9, you get compile errors if you try the swift 4 version with Xcode 8 (obviously).

**Comment by dirtmelon** [comment]
I found the Swift 4 version is using `NSAttributedStringKey`,such as @sample-repo say,NSAttributedStringKey works under iOS 11.0+.

**Comment by andreamazz** [comment]
@dirtmelon 
if you bothered to run it on iOS 10 you would have noticed that it runs with no issues. More so, this is the header for that symbol:
http://d.pr/i/XaXWJ
has no @available.

**Comment by dirtmelon** [comment]
sorry,that's my fault,I update podfile as #124 ,it compiles okay.Thank you very much :)
