### ISSUE TITLE
Vresion 3.0.0 doesn't compile with Xcode 9 GM + iOS 11

### ISSUE THREAD

**Issue by damianfitpotato** [andreamazz/AMPopTip#131]
Anyone else having issues compiling?

**Comment by andreamazz** [comment]
I'm using the GM seed and it compiles and run with no errors or warnings, maybe sharing the issue you are having could help.

**Comment by damianfitpotato** [comment]
![screen shot 2017-09-20 at 6 03 46 pm](https://user-images.githubusercontent.com/9097547/30633181-1bbd21dc-9e2e-11e7-8a84-bb42d7c98e3c.png)

**Comment by damianfitpotato** [comment]
![screen shot 2017-09-20 at 6 04 58 pm](https://user-images.githubusercontent.com/9097547/30633239-461b47d8-9e2e-11e7-8771-4a4efd29be3e.png)
![screen shot 2017-09-20 at 6 05 04 pm](https://user-images.githubusercontent.com/9097547/30633241-461bbdee-9e2e-11e7-83a3-ab0daa0d1265.png)
![screen shot 2017-09-20 at 6 05 10 pm](https://user-images.githubusercontent.com/9097547/30633240-461b9f80-9e2e-11e7-8330-36fc7097b6e9.png)

**Comment by andreamazz** [comment]
Using cocoapods? 
It looks like the pod is compiled with swift 3 instead of swift 4 (check your Pods project, the AMPopTip.framework target). See https://github.com/andreamazz/AMPopTip/issues/124 for a workaround.

**Comment by damianfitpotato** [comment]
Thanks for the reply! I've attached some screenshots.. compiles and works fine with 2.1.7

**Comment by damianfitpotato** [comment]
yes our project is not swift 4 yet.. is that supported?

**Comment by andreamazz** [comment]
https://github.com/andreamazz/AMPopTip#versioning-notes
Use version 2.x with swift 3.

**Comment by damianfitpotato** [comment]
Ok great thanks for the reply, will do
