### ISSUE TITLE
Manage PopTip of dynamic height in UITableViewCell

### ISSUE THREAD

**Issue by userSV** [andreamazz/AMPopTip#132]
how to set the frame of the AMPopTip when to be shown on button click in tableview cell. It is getting underneath the tableview cell.
![screen shot 2017-09-27 at 7 34 16 pm](https://user-images.githubusercontent.com/32333458/30917995-e8bf12ee-a3ba-11e7-9f70-a3d366db4b6b.png)

**Comment by gabdsg** [comment]
i have the same problem

**Comment by andreamazz** [comment]
At that point the poptip is just another UIView, if you ar presenting it in a view that clips content to its bounds, it will result clipped, as any other view would. You need to present it in the superview (i.e. the table view), with the proper presenting rect adjustment.
