### ISSUE TITLE
PopTip is partially displayed outside visible area of screen

### ISSUE THREAD

**Issue by akhilcb** [andreamazz/AMPopTip#133]
Thanks for the great library. I am trying to use this library to have a poptip without an arrow in my custom view on tap of a button. But for long text, the poptip is partially displayed outside the visible area of screen. This is my sample code:

```
let popTip = PopTip()
let newFrame = self.convert(sender.frame, to: self.window!)
popTip.show(text: "Hey! Listen! Some test string!", direction: .none, maxWidth: 400, in: self.window!, from: newFrame)
```

> Printing description of newFrame:
> ▿ (21.3333333333333, 190.0, 70.0, 32.0)

This is how it appears on the screen. How do I make sure that PopTip is always visible on the screen? I can see that if I specify the direction as anything other `.none`, it works fine.

<img width="231" alt="ampoptipoutsideviewbounds" src="https://user-images.githubusercontent.com/11095693/31757821-78631832-b45f-11e7-978a-f4c720565a98.png">

**Comment by andreamazz** [comment]
Mmmm, good point, I should probably add the same logic in the `.none`.  
Let me see if I can patch this in quickly...

**Comment by andreamazz** [comment]
Ok, that should do the trick. Let me know.

**Comment by akhilcb** [comment]
Thanks for the quick fix. It is working fine. A followup question, is it possible to set some padding to make sure the poptip origin is same as the button from which it appeared?(Right now it is touching the left edge) That way it will look like covering the button completely if I set maxWidth same as button.size.width. Text can wrap into multiple lines below the button too for long text.

**Comment by andreamazz** [comment]
`edgeMargin` should do the trick

**Comment by bennol** [comment]
Hi @andreamazz and thanks for the awesome library! 
I experienced some weird popover positioning with arrow direction .none after upgrading to 3.0.2 from the Obj-C version.

And tracked down the issue to rectContained() added recently. I added a comment with further details at: https://github.com/andreamazz/AMPopTip/commit/b9ceeb5855b614069bad361006ec3afcd606edc0
