### ISSUE TITLE
Incorrect arrow position for PopTipDirectionUp

### ISSUE THREAD

**Issue by GurovOK** [andreamazz/AMPopTip#134]
Thanks for the great library!
I add border to PopTip in demo project:
`popTip.borderWidth = 1`
`popTip.borderColor = .black`

result for PopTipDirectionUp:
![1](https://user-images.githubusercontent.com/3273368/32207695-3ba1b2ac-be30-11e7-856d-054c272e47b2.png)

PopTipDirectionDown:
![2](https://user-images.githubusercontent.com/3273368/32207731-76670680-be30-11e7-9029-001691b132f9.png)

Why arrow position is different?
Thanks in advance

**Comment by andreamazz** [comment]
Thanks to @bananabastard for the fix.
