### ISSUE TITLE
Add objective-c support to swift4 master branch

### ISSUE THREAD

**Issue by hardikamal** [andreamazz/AMPopTip#145]
Hi @andreamazz 
Thanks for the awesome library.
Can you plz add objective-c support to swift4 master branch, so that the new features can be used in objective-c too

**Comment by andreamazz** [comment]
Hi @hardikamal 
there are some features that are not supported in Objective-C, like enum's associated values. That's why I kept the versions separate. 
What are the features missing in the objective-c version? I can update that branch instead.

**Comment by hardikamal** [comment]
To update the position of ampoptip.

Also is there any way it can be used as Toast ie. appear for some time and go away automatically

**Comment by andreamazz** [comment]
> Also is there any way it can be used as Toast ie. appear for some time and go away automatically

Yes, check out the [readme](https://github.com/andreamazz/AMPopTip#dismissing-the-popover)

I'll add the position update to the 1.5.x branch.

**Comment by hardikamal** [comment]
one more thing...
Is there any way where we can queue the poptip for eg if one button is clicked poptip appears for some duration the other button is clicked the second poptip automatically appears after first one is hidden

**Comment by andreamazz** [comment]
I guess you can use the `dismissHandler` for that, anything more complex should reside in your app's logic.

**Comment by andreamazz** [comment]
Text update is up on the `v1.x` branch.

**Comment by andreamazz** [comment]
Closing this, let me know if you need further help.

**Comment by hardikamal** [comment]
Thanks.
