### ISSUE TITLE
Custom View with Border

### ISSUE THREAD

**Issue by Roost** [andreamazz/AMPopTip#151]
When showing the PopTip with a `customView` and having a `border`, the bubble layout is incorrect for all directions. Each direction has a different issue, but all of them incorrectly account for the size of the `customView` with respect to the `border` path that gets drawn.

**Comment by andreamazz** [comment]
Hey @Roost 
how are you drawing the border? I'm trying out a simple border on the view's layer and everything seem to be ok.

**Comment by HoDuyQuang** [comment]
@andreamazz Can I draw border arrow bubble and arrow? Or make a shadow? Would you please help me on this?

**Comment by andreamazz** [comment]
https://github.com/andreamazz/AMPopTip#customization

Shadow is not supported, I can add that.

**Comment by andreamazz** [comment]
Done, it's up in master
