### ISSUE TITLE
Argument 'in' must precede argument 'maxWidth'

### ISSUE THREAD

**Issue by UtkuDalmaz** [andreamazz/AMPopTip#158]
I am hving this error

<img width="958" alt="screen shot 2018-06-20 at 16 15 08" src="https://user-images.githubusercontent.com/2130592/41660602-393cd380-74a5-11e8-9784-4d10ca915bd9.png">

**Comment by andreamazz** [comment]
The order is fine. Sometimes swift throws that error when there is a typo in a named parameter, but those seem fine too. My next guess is the type of your prams, I reckon that `personalmsg` is not a CGRect instance.

**Comment by UtkuDalmaz** [comment]
personalmsg is UILabel. how can I do it right?

**Comment by andreamazz** [comment]
`personalmsg.frame`

**Comment by UtkuDalmaz** [comment]
Sorry but this UILabel is in a static tableview's section row. Pop appears on the top of tableview when I just use personalmsg.frame. How to use it in static tableview?

**Comment by andreamazz** [comment]
You need to transalte its coordiantes:
https://developer.apple.com/documentation/uikit/uiview/1622498-convertrect?language=objc

**Comment by Smiller193** [comment]
@andreamazz yea  I still get this error it is actually kind of weird
