### ISSUE TITLE
Not showing in Tabbar view

### ISSUE THREAD

**Issue by kashiftriffort** [andreamazz/AMPopTip#160]
Hi,

I need to show this in fourth tabbar place, I have passed values of frames, however its not showing exactly on fourth tab bar place, its showing before that, please confrim on this. Below is my code

    guard let view = self.tabBarController?.tabBar.items?[3].value(forKey: "view") as? UIView else
    {
      return
    }
    let frame = view.frame
    view.backgroundColor = UIColor.red
    let popTip = PopTip()
    popTip.show(text: "Hey! Listen!", direction: .up, maxWidth: 200, in: view, from: frame)

**Comment by kashiftriffort** [comment]
I have printd frame coordinates of view and its showing x & y coordinates as 0.

**Comment by andreamazz** [comment]
Wait, you are adding the poptip to the button, but offsetting it by its frame. You should either add the tip to the parent view with the translated absolute frame, or add it to the view, adjusting the frame accordingly. 
At this point, the poptip is just a basic UIView, you should treat it accordingly.
