### ISSUE TITLE
How to present popTip on certain UITableViewCell?

### ISSUE THREAD

**Issue by humunuku01** [andreamazz/AMPopTip#163]
Hey!

I want to show a PopTip on a certain cell in a UITableView. Is that possible? I tried to identify the proper cell in cellForRow - method and added a UIView in the custom cell. But the PopTip always points to the top row and not the row i specified.

Any thoughts would be of great appreciation!

Kind regards,
humunuku

**Comment by andreamazz** [comment]
Hey @humunuku01 
The poptip acts as a common UIView, so you need to provide the proper placement. If you add it to the tableview you need to [translate](https://developer.apple.com/documentation/uikit/uiview/1622498-convertrect?language=objc) the coordinates in relation to the table and also consider the content offset. Same goes if you add it tot the cell itself, at that point you need to translate your frame to the cell's frame.

**Comment by humunuku01** [comment]
Thank you very much! I experienced some problems displaying it in the cell directly, because the popup gets cut off as it exceeds the cells frame. I try the other approach you described. THANK YOU!

**Comment by andreamazz** [comment]
👍
