### ISSUE TITLE
Does not compile in Xcode Version 10.1 beta (10O23u)

### ISSUE THREAD

**Issue by NickSuglobov** [andreamazz/AMPopTip#169]
```
NotificationCenter.default.addObserver(self, selector: #selector(PopTip.handleApplicationActive), name: UIApplication.didBecomeActiveNotification, object: nil)
NotificationCenter.default.addObserver(self, selector: #selector(PopTip.handleApplicationResignActive), name: UIApplication.willResignActiveNotification, object: nil)
```

```
/AMPopTip/Source/PopTip.swift:465:125: 'didBecomeActiveNotification' has been renamed to 'NSNotification.Name.UIApplicationDidBecomeActive'
```

**Comment by andreamazz** [comment]
What?!  
Didn't they just rename it? The Swift 4.2 conversion suggested the change from `NSNotification.Name.UIApplicationDidBecomeActive` to `UIApplication.didBecomeActiveNotification`. 
Can someone shed some light on the matter?

**Comment by NickSuglobov** [comment]
@andreamazz Probably it's a converter issue.
I think the best solution is to support both old&new versions of Swift
using `#if swift(>=4.2)` `#else`

**Comment by NickSuglobov** [comment]
I found that the demo project `PopTip Demo` successfully compiles with Xcode 10.
Probably smth is wrong with my project setup. Closing the issue.
