### ISSUE TITLE
PopTip.swift file has error for UISwipeGestureRecognizer.Direction.right

### ISSUE THREAD

**Issue by sridhar-acceon** [andreamazz/AMPopTip#171]
It should be UISwipeGestureRecognizer.**direction**.right

**Comment by sridhar-acceon** [comment]
Also errors for applicationDidbecomeActive delegate calls

**Comment by andreamazz** [comment]
???
What Xcode version are you using?

**Comment by franiis** [comment]
I have the same problem. XCode 9.3 and Swift 4.1.
I'll investigate and post solution if I'll be able to found one.
