### ISSUE TITLE
Unable to Build because Xcode is Detecting Incorrect Parameter Labels

### ISSUE THREAD

**Issue by trevinwisaksana** [andreamazz/AMPopTip#172]
Hi,

I'm having issues with this library because Xcode seems to be asking me to change the argument labels of the function event though it seems to be correct. I've attached a screenshot for your reference. When I get Xcode to correct the function, it fails to do it and makes the parameters look bizarre.

Do you have any suggestions? I tried reinstalling the pod, restarting Xcode and cleaning the build folder but it didn't work.

Thanks!

<img width="906" alt="screenshot" src="https://user-images.githubusercontent.com/20000813/51071614-80922180-1686-11e9-9d28-2eaa362a3c5a.png">

**Comment by andreamazz** [comment]
Check out this issue: https://github.com/icanzilb/SwiftSpinner/issues/132

**Comment by andreamazz** [comment]
@trevinwisaksana 
any luck? I'm testing the demo app and it's working fine.

**Comment by Smiller193** [comment]
@andreamazz  i am facing the same issue

**Comment by andreamazz** [comment]
If you don't provide more context or, even better, a sample project showing the issue I don't know what I can possibly do.

**Comment by andreamazz** [comment]
> Hi,
> 
> I'm having issues with this library because Xcode seems to be asking me to change the argument labels of the function event though it seems to be correct. I've attached a screenshot for your reference. When I get Xcode to correct the function, it fails to do it and makes the parameters look bizarre.
> 
> Do you have any suggestions? I tried reinstalling the pod, restarting Xcode and cleaning the build folder but it didn't work.
> 
> Thanks!
> 
> <img alt="screenshot" width="906" src="https://user-images.githubusercontent.com/20000813/51071614-80922180-1686-11e9-9d28-2eaa362a3c5a.png">

Ok, I think I see the problem now, the parameter `from:` accepts a `CGRect`, you are providing a `UIView`

**Comment by andreamazz** [comment]
Yep, can confirm that passing a UIView causes that error. It's a bit obscure on the compiler's part, but the type system is there for a reason.
