### ISSUE TITLE
Firing tapHandler on popTip and frame area tap

### ISSUE THREAD

**Issue by morgan-legal** [andreamazz/AMPopTip#173]
👋

First of all, thank you for this library! It does about everything I need, there's just one thing missing or I'm not aware of;

Is there a way to fire the tapHandler if the user touches the area where the popTip is pointing to ? 

My popTip needs to be dismissed on tap outside of it.

In the attached image, this explains what I'm looking to achieve. 
The red and purple area needs to fire the tapHandler and the white area the dismissHandler.

<img width="286" alt="tooltip" src="https://user-images.githubusercontent.com/11411520/51196237-01ebed00-18ef-11e9-986b-ce86b2fb7054.png">

Thanks.

**Comment by andreamazz** [comment]
Hi @morgan-legal 
your best option is to attach a tap handler to your object separately, doing so from the poptip would be overkill in my opinion.

**Comment by morgan-legal** [comment]
Hi @andreamazz,

Thanks for your quick reply. 

Actually, this won't be possible. The red view already has a tapHandler. The thing is, I set both booleans `shouldDismissOnTap` & `shouldDismissOnTapOutside` to true, which results on my red view's tapHandler not being triggered. And I want (need) those two booleans to be equal to true because I don't want any other views in my controller to be tappable. I really want to emphasize this red view and leave its handler enabled. Both taps (red view & popTip view) would fire the same action.

Is there any way to add a boolean which could tell the view to fire the popTip tapHandler also when the user taps the frame that we pass to the popTip ?

**Comment by Kaspik** [comment]
PR https://github.com/andreamazz/AMPopTip/pull/174 has been merge in and new version released! This can be closed now. :)
