### ISSUE TITLE
Ambiguous use of 'cornerRadius'

### ISSUE THREAD

**Issue by tommyyoon** [andreamazz/AMPopTip#177]
I am getting Ambiguous use of 'cornerRadius' error when I try to set the cornerRadius on Swift 4.2.

**Comment by andreamazz** [comment]
Hey @tommyyoon 
It's not a library issue, maybe the problem relies on your configuration

**Comment by anonrig** [comment]
I'm having the same issue. I think that this is a library issue. I'm having this issue with all shadow related attributes.

Any idea why @andreamazz

**Comment by anonrig** [comment]
There's 2 shadowOpacity defined in my scope.

1. AMPopTip attribute shadowOpacity
2. QuartzCore's CALayer attribute shadowOpacity

**Comment by anonrig** [comment]
Shouldn't the library override the shadoowOpacity attribute since PopTip is a UIView? This is my configuration:

```swift
let tip = PopTip()
                tip.font = UIFont.mediumFont(size: 14)
                tip.textColor = UIColor(hex: 0x2f2f2f)!
                tip.layer.shadowOffset = CGSize(width: 0, height: 2)
                tip.layer.shadowRadius = 4
                tip.layer.shadowOpacity = 0.06
                tip.layer.shadowColor = UIColor.black.cgColor
                tip.bubbleColor = .white
                tip.shouldDismissOnTapOutside = true
                tip.offset = 8
                tip.edgeInsets = UIEdgeInsets(top: 10, left: 12, bottom: 10, right: 12)
                tip.layer.cornerRadius = 10
                tip.show(text: "Added to favorites!", direction: .left, maxWidth: 164, in: self.viewSource, from: self.viewSource.favoriteButton.frame)
```

Since on `draw` function you are overriding `tip.layer` attributes, even if I set them beforehand, it gets override, and `tip.shadowOpacity` gives an ambiguous error.

**Comment by andreamazz** [comment]
In hindsight, the shadow properties of the layers could've been left alone, except for the shadowPath, which uses an internal bezier path. 
However, you should have no ambiguous errors, I've just tested the demo project, and there are no errors or warnings.
