### ISSUE TITLE
Use of unresolved identifier 'PopTip'

### ISSUE THREAD

**Issue by nAviram** [andreamazz/AMPopTip#180]
I've followed the installation instructions, and I got this build error:

> Use of unresolved identifier 'PopTip'

when I did:
_**let popTip = PopTip()**_

**Comment by andreamazz** [comment]
Did you import the framework?
```
import AMPopTip
```

**Comment by nAviram** [comment]
👍   forgot that!!!  :-P  
thanks for the fast reply!!!
(and maybe you should add this line to the instructions for lazy people like me)

**Comment by andreamazz** [comment]
> (and maybe you should add this line to the instructions for lazy people like me)

Yep, I just did 😬
