### ISSUE TITLE
how can I open a link in a pop tip when the text is NSAttributedString ?

### ISSUE THREAD

**Issue by nAviram** [andreamazz/AMPopTip#181]
I have a pop-tip with a link inside, but when I click on in the pop-tip closes.
how can I make it open the link?

**Comment by andreamazz** [comment]
```swift
popTip.shouldDismissOnTap = true

popTip.tapHandler = { _ in
  print("tap")
}
```

**Comment by rivera-ernesto** [comment]
I'm hitting a limitation here.

I have many buttons in my custom view, but the poptip hijacks the taps. Same would happen with a custom view with a list of options.
The handler limitation is that all the area is recognized as a tap.

**Comment by andreamazz** [comment]
Mh, not sure what do though, this was thought out as a common UIView with a gesture recognizer attached, that's standard UIKit behavior.

**Comment by rivera-ernesto** [comment]
It seems that the issue is with the new custom SwiftUI views. For some strange reason `.onTapGesture` doesn`t work.
