### ISSUE TITLE
Offset the arrow

### ISSUE THREAD

**Issue by flyOfYW** [andreamazz/AMPopTip#184]
I want to move the arrow, now that the arrow is centered by default, can you set the arrow to go a little bit to the left or a little bit to the right @andreamazz

**Comment by andreamazz** [comment]
`bubbleOffset` should do the trick if I remember correctly.

**Comment by flyOfYW** [comment]
I have set the value of bubbleOffset, but I found that it is not good. So I asked you for advice

**Comment by andreamazz** [comment]
"not good" how? Please elaborate a bit so I can help you, an example would be great too.

**Comment by flyOfYW** [comment]
bubbleOffset=80 or bubbleOffset=-80,The arrow is still in the middle
![5862F334-D42F-4893-9A2A-294A56D3DEB9](https://user-images.githubusercontent.com/17938752/56114207-c2d34380-5f92-11e9-84d8-bc88e48015bb.png)
This is what I want

**Comment by andreamazz** [comment]
What frame are you presenting it from? If it doesn't move I reckon that the frame is too narrow.

**Comment by flyOfYW** [comment]
//MARK: -- show
    func show(direction:PopDirection,inView:UIView,from:CGRect,arrowPosition:CGPoint = CGPoint.zero) -> Void{
        let viewWidth:CGFloat = 200
        let viewHeight:CGFloat = 300
        if self.frame.height != viewHeight {
            self.frame = CGRect.init(x: 0, y: 0, width: viewWidth, height: viewHeight)
        }
        self.popView.arrowPositionNew = arrowPosition
        switch direction {
        case .up:
            self.popView.show(customView: self, direction: .up, in: inView, from: from)
        case .down:
            self.popView.show(customView: self, direction: .down, in: inView, from: from)
        case .left:
            self.popView.show(customView: self, direction: .left, in: inView, from: from)
        case .right:
            self.popView.show(customView: self, direction: .right, in: inView, from: from)
        default:
            self.popView.show(customView: self, direction: .none, in: inView, from: from)
        }
        self.popView.tapOutsideHandler = { _ in
            print("tap outside")
        }

**Comment by andreamazz** [comment]
I mean, whats the `from` frame and what's the `inview`?

**Comment by flyOfYW** [comment]
Window

**Comment by andreamazz** [comment]
Scratch that, I was misremembering, `bubbleOffset` moves the whole thing. 
This feature is not implemented. You can work around it by adjusting the fames you are presenting stuff from, but that's it. 
If anyone wants to pitch in this can be a good entry point.

**Comment by flyOfYW** [comment]
I currently do this by inheriting PopTip and rewriting draw
