### ISSUE TITLE
bubbleOffset not working as documented

### ISSUE THREAD

**Issue by andrew-muzmatch** [andreamazz/AMPopTip#186]
Firstly, thanks for the great framework and all your effort in maintaining it!

So I'm not sure if this a problem with the docs, a bug or some gotcha that I'm yet to uncover but bubbleOffset is not working for me as documented.

The documents state that:
> The arrow is centered by default, and moves to avoid the edge of the screen. You can manually change the offset from the center using the bubbleOffset property.

This suggests to me that that the arrow can be offset from the center of the bubble.
Having said that whenever I try to use bubbleOffset the whole bubble is offset rather than the arrow.

I'm trying to get my bubble horizontally aligned within the screen but the arrow offset to point to something which isn't horizontally aligned.

Any idea what could be causing this?

**Comment by andreamazz** [comment]
Hi @andrew-muzmatch 
the documentation in the readme is wrong, in the code it reads:
```
Holds the offset between the bubble and origin
```
it's not intended to be the arrow's offset. 

I've added the property `arrowOffset`. It's just a float value, can be positive or negative (it's relative to the center), and is clamped to the bubble size.

**Comment by andreamazz** [comment]
Released `4.1.0`. Let me know if that works for you.

**Comment by andrew-muzmatch** [comment]
Hi @andreamazz
Sorry for the delay.
Just got around to updating and checking the functionality.
Looks great and arrowOffset works for me.
Thank you for your hard work getting that functionality in!
