### ISSUE TITLE
popTip in UITableViewController

### ISSUE THREAD

**Issue by Begoodi** [andreamazz/AMPopTip#187]
I'm trying to implement PopTip on a table view when user taps on a row cell.
Tried many things for in: and from: but nothing happens. The tooltip is active but not displayed.

```swift
    override func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        if let cell = tableView.cellForRow(at: indexPath) {
            print("tooltip")
            let popTip = PopTip()
            popTip.show(text: "Hey! Listen!", direction: .up, maxWidth: 200, in: tableView, from: cell.frame, duration: 2)
        }
    }
```

Thanks for your help :)

**Comment by andreamazz** [comment]
Seems to display just fine with your code, check out this sample project:

[TipTable.zip](https://github.com/andreamazz/AMPopTip/files/3289958/TipTable.zip)

**Comment by Begoodi** [comment]
Hi, thanks a lot, that's right it works on your example.
In fact I selected a subview of the cell with a specified tag, and with that it's not working...
```
if let cell = tableView.cellForRow(at: indexPath).viewWithTag(100) {
    ...
}
```
So I remove viewWithTag and did it in another way.

Thanks for your help, great popup, simple and efficient !
