### ISSUE TITLE
How to Have Tap Forward to Underlying Views

### ISSUE THREAD

**Issue by samhinsh** [andreamazz/AMPopTip#188]
Hi there - is there a suggested way to have taps forward to underlying views?

For example, if a tooltip is displaying and pointing to a button or a cell, is there a simple way to tap that item and have the touch carryover without having to tap twice? (_"Tap twice"_ meaning the where first tap dismisses the tooltip, and the second tap is actually received by the button/cell/UI element)

**Comment by andreamazz** [comment]
Hi @samhinsh 
An easy solution to this would be disabling user interactions on the pop tip (with `isUserInteractionEnabled`) and handle its dismiss in the tap handler o your button/cell.

**Comment by samhinsh** [comment]
Hmm that's a great suggestion. I did try that, but the behavior of the tooltip seems to be the same:

```let tooltip = PopTip()```
```tooltip.isUserInteractionEnabled = false```

**Comment by andreamazz** [comment]
Here's a working sample:
https://d.pr/f/V7aIub

As you can see the action is called even when you tap on the poptip

**Comment by samhinsh** [comment]
Ok, thank you

**Comment by rivera-ernesto** [comment]
Pasting the code here so we don't need to download the sample to see it.
Also it may be a common enough use to mention in in the README.

```swift
class ViewController: UIViewController {
  let popTip = PopTip()
  
  override func viewDidLoad() {
    super.viewDidLoad()
  }

  @IBAction func showTip(sender: UIButton) {
    popTip.isUserInteractionEnabled = false
    popTip.show(text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris id nulla lorem. ", direction: .up, maxWidth: 200, in: self.view, from: sender.frame)
  }

  @IBAction func otherAction() {
    print("action")
    popTip.hide()
  }
  
}
```
