### ISSUE TITLE
Tooltip does not hide on iOS13

### ISSUE THREAD

**Issue by AleLudovici** [andreamazz/AMPopTip#189]
I'm calling the `hide method` of `AMPopTip.m` to dismiss a `OOGAMPopTip` view. It works fine for iOS 12 but not for iOS 13. 
Debugging the problem I've found that `[self performExitAnimation:^{` is never executed.
Is there anyone with the same problem?

**Comment by andreamazz** [comment]
Hey @AleLudovici 
I've just tested the most recent version with iOS13 beta 3 and it's working fine.
Is there any way you can upgrade to the swift version of the library?

**Comment by AleLudovici** [comment]
@andreamazz thank you for the quick response. I've just tested on a real device with iOS13 and it works fine. I had some problem with the simulator. Hopefully it's not an issue at all. Will keep an eye on it If I see this issue coming back.
