### ISSUE TITLE
AMPopTip has no Package.swift manifest for version 4.1.0

### ISSUE THREAD

**Issue by chengkaizone** [andreamazz/AMPopTip#193]
AMPopTip is perfect, but I can't load the resolve using the Xcode 11 Swift Package add-on library, which prompts the following error: "https://github.com/andreamazz/AMPopTip has no Package.swift manifest for version 4.1.0", Package.swift The file is not perfect, I hope it can be solved
Thank you

**Comment by andreamazz** [comment]
Hey @chengkaizone 
try now, I forgot to push a new version, it should be ok now
