### ISSUE TITLE
Shadow not animate when PopTip update custom view

### ISSUE THREAD

**Issue by imzark** [andreamazz/AMPopTip#199]
I use PopTip with shadow config and show a custom view that would change its frame later.
So I code like:
```
popTip.shadow = ...
popTip.show(customView: myCustomView, ....)
...
// After myCustomView frame changed
popTip.update(customView: myCustomView)
```

The problem is PopTip's frame animate correctly but the shadow change immediately. It seems like the override draw() function redraw the shadowPath without animation.

Any ideas about the situation?

**Comment by andreamazz** [comment]
Yeah, good point, the shadow animation should go inside a `CoreGraphics` animation. Let me check

**Comment by andreamazz** [comment]
Can you check the latest commit on master? It should fix the issue

**Comment by imzark** [comment]
@andreamazz Cool it works!  🎉 🎉  Thanks
