### ISSUE TITLE
Automatic custom view direction on screen

### ISSUE THREAD

**Issue by simformsolutions** [andreamazz/AMPopTip#205]
This is awesome library but if it would be possible to add one more option for showing the content view on any direction of the screen.
Currently I have used this to show custom view with direction .down but the issue is it shows custom view out of the screen.
I think if you would add this functionality which would help us to automatically detect the direction of custom view.

**Comment by andreamazz** [comment]
Hi @simformsolutions 
I'm not sure I understand, can you provide a simple? Even a simple sketch would do.

**Comment by simformsolutions** [comment]
Currently we have to hardcoded give **PopTipDirection** like .up, .down, .left , .right or .none
There must be one more case **.any** which could automatically detect the content view direction.
If **.any** is used then the content view will not go out of screen as well.

**Comment by andreamazz** [comment]
Ok, makes sense. Let me see if I can come up with something.

**Comment by andreamazz** [comment]
I've added three new directions: 
- `auto`: picks a direction between `up`, `down`, `left` and `right`
- `autoHorizontal`: picks a direction only between `left` and `right`
- `autoVertical`: : picks a direction only between `up` and `down` 

Let me know how it goes

**Comment by andreamazz** [comment]
🤷
