### ISSUE TITLE
Example of using AMPopTip in SwiftUI View?

### ISSUE THREAD

**Issue by neilt** [andreamazz/AMPopTip#207]
It is not clear to me how to use AMPopTip in a SwiftUI project.

Now that is probably because I am new to SwiftUI and have no clue.  

I see from the Demo project that you have an example to show a SwiftUI View in a conventional UIView/UIViewController.

What I am interested in is having a PopTip shown in response to a SwiftUI button press.

For example:
```
	Button(action: {
		PopTip().show(??, ??, ??, etc)
	}) {
		Image(systemName: "questionmark.circle")
			.font(.system(.title))
			.foregroundColor(.blue)
	}
```

Is this possible?

**Comment by andreamazz** [comment]
Hi @neilt 
No, it's not possible, the PopTip is a basic `UIView`, it can show a SwfitUI view (see the sample project), but can't be mounted as is inside a SwiftUI view. You'll need to look into `UIViewRepresentable`.
