### ISSUE TITLE
How to import into an Objective C project?

### ISSUE THREAD

**Issue by primehalo** [andreamazz/AMPopTip#208]
I was using this in my Objective C project and it worked great. I recently updated the Pod to the latest version and now I can't seem to figure out how to import it. The previous method no longer works:
`#import <AMPopTip/AMPopTip.h>`

I read that this was converted to Swift so I found info about importing Swift code into Objective C on Apple's site:

> Import Code Within a Framework Target
> 
> To import a set of Swift files in the same framework target as your Objective-C code, import the Xcode-generated header for your Swift code into any Objective-C .m file where you want to use your Swift code.
> 
> Because the generated header is part of the framework’s public interface, only declarations marked with the public or open modifier appear in the generated header for a framework target. Methods and properties that are marked with the internal modifier and declared within a class that inherits from an Objective-C class are accessible to the Objective-C runtime. However, they're inaccessible at compile time and don't appear in the generated header for a framework target.
> 
> Import Swift code into Objective-C within the same framework:
> 
> 1. Under Build Settings, in Packaging, make sure the Defines Module setting for that framework target is set to Yes.
> 
> 2. Import the Swift code from that framework target into any Objective-C .m file within that target using this syntax and substituting the appropriate names:
> 
> `#import <ProductName/ProductModuleName-Swift.h>`

I set **Defines Module** to **Yes** for AMPopTip and then changed the import to this:
`#import <AMPopTip/AMPopTip-Swift.h>`

But it still says the file isn't found. The README.md file simply says:
`import AMPopTip`

I assume that is for Swift because it doesn't work for Objective C. Can someone fill me in on how to include this in an Objective C project?

**Comment by andreamazz** [comment]
Hey @primehalo 
You would normally use the `@import` directive, like this:
```
@import AMPopTip;
```

Unfortunately this version is not compatible with Objective-C, since it uses some Swift-only features, so you'll need to keep using version `1.5.x`

**Comment by mmkarlosmm** [comment]
ا
