### ISSUE TITLE
Make it easier to handle screen orientation change

### ISSUE THREAD

**Issue by mmcdole** [andreamazz/AMPopTip#21]
We are using AMPopTip in an app that supports both Portrait and Landscape.  When a user rotates their device while a tooltip is visible, it obviously will now point at an incorrect location.

I know that AMPopTip is just a UIView that I'm free to position myself.  However, all the calculation for how to position the tooltip correctly is internal to AMPopTip and I'd rather not recreate this myself.

Would it be possible to expose a method that lets me update the "fromFrame" such that pop-tip will re-do it's ```setup``` method with that new frame?  That way on rotate I can check for any AMPopTip's where ```isVisible``` is ```YES``` and I'll send a new fromFrame to them?

**Comment by andreamazz** [comment]
Closing this one. Feel free to reopen if needed.
