### ISSUE TITLE
Unknown UILabel above custom view

### ISSUE THREAD

**Issue by pxc052** [andreamazz/AMPopTip#212]
UIButton event can't be triggered, so I open view hierarchy and notice that there is a UILabel over customView.
I think that this UILabel prevent any action on UIButton.

```
    let customView = CustomView(frame: CGRect(x: 0, y: 0, width: 330, height: 116))
    customView.button.addTarget(self, action: #selector(handleTap), for: .touchUpInside)
    popTip.shouldDismissOnTap = false
    popTip.shouldDismissOnTapOutside = false
    popTip.shouldDismissOnSwipeOutside = false
    popTip.dismissHandler = {
        self.popTip.hide()
    }
    popTip.show(customView: customView, direction: .down, in: topView,  from: button.frame)


    @objc func handleTap() {
        print("Tapped")
    }
```

![Screen Shot 2020-10-27 at 3 55 56 PM](https://user-images.githubusercontent.com/30617030/97279014-02a80600-186d-11eb-999e-5f3e7f530ae8.png)

**Comment by andreamazz** [comment]
Hey @pxc052 
Checkout the latest commit on master and let me know if that helps.
