### ISSUE TITLE
popTip in UITableViewController in cell's UIButton

### ISSUE THREAD

**Issue by Yagnik13** [andreamazz/AMPopTip#213]
**Describe the bug**
i'm trying to implement on inside cell on UIButton
but it will display like below image 

![Screenshot 2020-10-28 at 10 46 47 AM](https://user-images.githubusercontent.com/22394797/97395401-e3f84c80-190a-11eb-90df-be6383267b1d.png)

i'm also tried to change frame but not get success in that.

**To Reproduce**
1. create one cell and but UIButton on right side and try to implement this
- is it possible to dismiss on tableview scroll ?

**Expected behavior**
Display any direction but exact 3 dot button position(frame)

like below image
![Screenshot 2020-10-28 at 10 52 24 AM](https://user-images.githubusercontent.com/22394797/97395782-ad6f0180-190b-11eb-8355-ffc66dc7136e.png)

**Comment by andreamazz** [comment]
Hey @Yagnik13 
can you post the code you are using to display it? It's just a matter of setting the appropriate frame.

You can dismiss on scroll, just tap into the tableView's scrollview delegate.
