### ISSUE TITLE
CoreGraphics API passed "NAN"

### ISSUE THREAD

**Issue by cyg02032015** [andreamazz/AMPopTip#215]
**Describe the bug**
When i use show(custom:direction:in:from:duration)

debug console will print "Error: this application, or a library it uses, has passed an invalid numeric value (NaN, or not-a-number) to CoreGraphics API and this value is being ignored. Please fix this problem."

**To Reproduce**
This is my code
```swift
        popTip.shouldDismissOnTap = true
        popTip.shouldDismissOnTapOutside = true
        popTip.shouldDismissOnSwipeOutside = true
        popTip.bubbleColor = .clear
        popTip.edgeInsets = .zero
        popTip.padding = 0.0
        popTip.arrowSize = .zero
        ....
        self.popTip.show(customView: popView, direction: .up, in: self, from: frame, duration: 3)
```

**Expected behavior**
When i create a symbold breakpoint with CGPostError
It will be crash in PopTip+Draw.swift line 72
cornerPoint.x cornerPoint.y is Nan

How can i fix this?

**Comment by andreamazz** [comment]
Turns out that no matter how hard you try, you can't divide by zero. 
The `zero` as `arrowSize` was causing this issue, it should be now fixed.

Thanks for the feedback

**Comment by cyg02032015** [comment]
Thanks 👍👍👍
