### ISSUE TITLE
I can't set the borderWidth and the cornerRadius

### ISSUE THREAD

**Issue by DevTonyXu** [andreamazz/AMPopTip#219]
when I use the poptips to set it's pragram,the project show me these error

**Comment by andreamazz** [comment]
Hi @DevTonyXu 
it's not an issue in the library, the demo project runs fine, so I reckon there's something wrong in your integration. What are you using to integrate the library in your project?

**Comment by DevTonyXu** [comment]
> Hi @DevTonyXu
> it's not an issue in the library, the demo project runs fine, so I reckon there's something wrong in your integration. What are you using to integrate the library in your project?

YES，it's not a issue， I  have found what bring my error infos，thank for your reply
