### ISSUE TITLE
Failed  github "andreamazz/AMPopTip" ~> 4.5.3  Carthage update in Xcode 13 beta 5 

### ISSUE THREAD

**Issue by madhusudhanraoch** [andreamazz/AMPopTip#221]
*** Checking out AMPopTip at "4.5.3"
*** xcodebuild output can be found in /var/folders/x8/dnk5cymd3wz1w_ccvz755pr00000gq/T/carthage-xcodebuild.OpOw6e.log
*** Building scheme "AMPopTip" in PopTip Demo.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/safuan/Desktop/NinthList/Carthage/Checkouts/AMPopTip/Demo/PopTip\ Demo.xcworkspace -scheme AMPopTip -configuration Release -derivedDataPath /Users/safuan/Library/Caches/org.carthage.CarthageKit/DerivedData/13.0_13A5212g/AMPopTip/4.5.3 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive VALIDATE_WORKSPACE=NO -archivePath /var/folders/x8/dnk5cymd3wz1w_ccvz755pr00000gq/T/AMPopTip SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/safuan/Desktop/NinthList/Carthage/Checkouts/AMPopTip)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/x8/dnk5cymd3wz1w_ccvz755pr00000gq/T/carthage-xcodebuild.OpOw6e.log

/Users/safuan/Desktop/NinthList/Carthage/Checkouts/AMPopTip/Source/PopTip.swift:10:27: error: failed to build module 'Combine'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.5 (swiftlang-1300.0.29.1 clang-1300.0.28.1)', while this compiler is 'Apple Swift version 5.5 (swiftlang-1300.0.29.102 clang-1300.0.28.1)'). Please select a toolchain which matches the SDK.
#if canImport(SwiftUI) && canImport(Combine)
                          ^

* ARCHIVE FAILED *

The following build commands failed:
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'AMPopTip' from project 'Pods')
	CompileSwiftSources normal armv7 com.apple.xcode.tools.swift.compiler (in target 'AMPopTip' from project 'Pods')
	CompileSwift normal armv7 (in target 'AMPopTip' from project 'Pods')

**Comment by andreamazz** [comment]
This is a known issue in Xcode 13 beta 5, see release note:

    Swift libraries may fail to build for iOS targets that use armv7. (74120874)
    Workaround: Increase the platform dependency of the package to v12 or later.

**Comment by madhusudhanraoch** [comment]
> This is a known issue in Xcode 13 beta 5, see release note:
> 
> ```
> Swift libraries may fail to build for iOS targets that use armv7. (74120874)
> Workaround: Increase the platform dependency of the package to v12 or later.
> ```

Can possible to change package to v12 or later from my side ?? I Had same issue with other Libraries the updated Package.swift to v12. Can possible to edit your side
