### ISSUE TITLE
Carthage Update for XCODE 13 RC failed.

### ISSUE THREAD

**Issue by madhusudhanraoch** [andreamazz/AMPopTip#223]
*** Checking out AMPopTip at "4.5.3"
*** xcodebuild output can be found in /var/folders/x8/dnk5cymd3wz1w_ccvz755pr00000gq/T/carthage-xcodebuild.nhoBhX.log
*** Building scheme "AMPopTip" in PopTip Demo.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/safuan/Desktop/FourthList/Carthage/Checkouts/AMPopTip/Demo/PopTip\ Demo.xcworkspace -scheme AMPopTip -configuration Release -derivedDataPath /Users/safuan/Library/Caches/org.carthage.CarthageKit/DerivedData/13.0_13A233/AMPopTip/4.5.3 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive VALIDATE_WORKSPACE=NO -archivePath /var/folders/x8/dnk5cymd3wz1w_ccvz755pr00000gq/T/AMPopTip SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/safuan/Desktop/FourthList/Carthage/Checkouts/AMPopTip)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/x8/dnk5cymd3wz1w_ccvz755pr00000gq/T/carthage-xcodebuild.nhoBhX.log

** ARCHIVE FAILED **

The following build commands failed:
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'AMPopTip' from project 'Pods')
	CompileSwiftSources normal armv7 com.apple.xcode.tools.swift.compiler (in target 'AMPopTip' from project 'Pods')
	CompileSwift normal armv7 (in target 'AMPopTip' from project 'Pods')

**Comment by andreamazz** [comment]
Hey @madhusudhanraoch 
As far as I can tell it's an issue with Carthage, not the library. Looks like it's not handling the precompiler `canImport`.

**Comment by szotp** [comment]
This can be reproduced without carthage by trying to archive the framework.

To solve this, just raise minimal iOS target to 11 - this will exclude armv7 from building.
