### ISSUE TITLE
XCode 13 release build and archive issue

### ISSUE THREAD

**Issue by denizavsar** [andreamazz/AMPopTip#224]
**Describe the bug**
With the new Xcode 13, I can't either archive the project or get a release build but everything works well with debug build. 

I found a temporary solution to that situation. I increased the pod's minimum iOS version 9 to 11 and it worked. 

Can u guys give me more info about that issue?

**To Reproduce**
1. Install AMPopTip (4.5.3) on any project
2. Try to archive the project with official XCode 13
3. Errors on the screenshot will occur

**Expected behavior**
Build properly.

**Screenshots**

<img width="287" alt="Screen Shot 2021-09-21 at 13 37 34" src="https://user-images.githubusercontent.com/37863246/134156604-135d7dac-92f3-4ba1-800f-ad8e52f3846d.png">

**Comment by netcosportsanatoly** [comment]
Bumping the minimum target isn't a solution
