### ISSUE TITLE
Xcode 13 build error

### ISSUE THREAD

**Issue by StasKeiss** [andreamazz/AMPopTip#226]
There is an issue that you fixed for pods, referenced here: https://github.com/andreamazz/AMPopTip/issues/224.

But it still happens if you use SPM. Any workaround for that?

Thanks

**Comment by paulstampfer** [comment]
I have the same issue and need an urgent fix. What can be done here?

**Comment by andreamazz** [comment]
Check out the latest commit from https://github.com/andreamazz/AMPopTip/pull/225
I'm beyond swamped right now so I can't check it out

**Comment by paulstampfer** [comment]
Thanks @andreamazz I changed the package in SPM to the commit you mentioned and it works fine. Now I can archive the app.

**Comment by andreamazz** [comment]
Awesome, thanks to  @bpollman 
I'll cut a new release

**Comment by andreamazz** [comment]
4.6.1 released

**Comment by StasKeiss** [comment]
Thank you!
