### ISSUE TITLE
Tip either doesn't display or displays in wrong spot

### ISSUE THREAD

**Issue by yismo** [andreamazz/AMPopTip#23]
Hi, I'm using this with Swift and a bridging header so that could be the reason it't not working. 

I basically want the tip to appear as soon as the app is open:

        var popTip = AMPopTip()

        override func viewDidAppear(animated: Bool) {
        super.viewDidAppear(true)
        
        popTip.showText("If you like the quote, swipe the card to the right…otherwise swipe to the left! ", direction: AMPopTipDirection.Down, maxWidth: 260, inView: self.view, fromFrame:card1.frame)
    }

Any ideas? Thanks :)

**Comment by andreamazz** [comment]
Hi @yismo 
I tried with a new project, using your code, and it seems to be working fine. I used the code in [this gist](https://gist.github.com/andreamazz/5ab0b4fd667ef912dce6).  
It might have something to do with your view's layout, have you checked with the View Hierarchy inspector to check wether the poptip is covered by another view?

**Comment by andreamazz** [comment]
Closing this, feel free to reopen if you are still experiencing the issue and can provide further information.
