### ISSUE TITLE
Ambiguous use of 'cornerRadius'

### ISSUE THREAD

**Issue by wfs498121294** [andreamazz/AMPopTip#230]
Hello  help me  thanks

Ambiguous use of 'cornerRadius'
Ambiguous use of 'borderWidth'

        let popTip = PopTip()
        popTip.cornerRadius = 5  
        popTip.borderWidth = 0.5
        popTip.textColor = textBlackColor!
        popTip.bubbleColor = textWhiteColor!
        popTip.borderColor = viewBackgroundCDColor!

**Comment by andreamazz** [comment]
https://github.com/andreamazz/AMPopTip/issues/219
https://github.com/andreamazz/AMPopTip/issues/177

**Comment by wfs498121294** [comment]
thanks
