### ISSUE TITLE
Unable to pod install 4.6.1

### ISSUE THREAD

**Issue by EZL-ivanloh** [andreamazz/AMPopTip#231]
Hello, 
I just upgraded to Xcode 13.1 and face the issue below. 

![image](https://user-images.githubusercontent.com/84302678/146294756-92714976-0388-4471-bd60-6d8779079beb.png)

I have tried upgrading the pods from my existing (4.4.0) to the latest (4.6.1) via cocoapod command line, it fails to update. I am able to upgrade to (4.5.3) and but not (4.6.0 or 4.6.1). 

![image](https://user-images.githubusercontent.com/84302678/146294921-f197e1e1-2c6d-4bb8-9298-2c0b8352fb7c.png)

Can you please advise on the above on how can i upgrade to the latest (4.6.1) via cocoapod?

**Comment by andreamazz** [comment]
My Podfile:
```
target 'something' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'AMPopTip', '4.6.1'

end
```
results in:
```
> pod install
Analyzing dependencies
Downloading dependencies
Installing AMPopTip (4.6.1)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `test.xcworkspace` for this project from now on.
Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.
```
