### ISSUE TITLE
Crashes while launching the app

### ISSUE THREAD

**Issue by Pravalika-Donthineni** [andreamazz/AMPopTip#233]
**After updating to 4.6.1, The pod crashes while launching the app**
[](url)
 **Error in Xcode command line:** dyld[77051]: Library not loaded: @rpath/AMPopTip.framework/AMPopTip

Below is the dyld error:
<img width="954" alt="Screen Shot 2022-01-12 at 3 01 55 PM" src="https://user-images.githubusercontent.com/54910898/149213264-5e016370-b5fe-4e48-acfd-aa5a3c94effd.png">

**Comment by Iniyarajan** [comment]
Any solution?

**Comment by andreamazz** [comment]
Please provide more context, this usually is just a misconfiguration at the project level, nothing related to the library
