### ISSUE TITLE
Problem with UICollectionView

### ISSUE THREAD

**Issue by renjithn** [andreamazz/AMPopTip#29]
When PopTip is used on a UICollectionViewCell area didSelectItemAtIndexPath: delegate does not get called. I believe this could be the effect of the "remove" gesture recognizer which is not required in my particular case.

Was able to fix this by adding;
```objc
- (void) setShouldDismissOnTapOutside:(BOOL)shouldDismissOnTapOutside
{
    _shouldDismissOnTapOutside = shouldDismissOnTapOutside;
    _removeGesture.enabled = shouldDismissOnTapOutside;
}
```

**Comment by andreamazz** [comment]
Hi @renjithn 
Nice catch, I'll integrate this fix in the next release. Thank you

**Comment by CIAlexanderAkimov** [comment]
Current AMPopTip Swift version (2.1.5) has the same issue.
"popTip.shouldDismissOnTapOutside = false" doesn't disable gesture recornizer.

**Comment by andreamazz** [comment]
@CIAlexanderAkimov  Fixed in the latest version
