### ISSUE TITLE
Rounded arrow

### ISSUE THREAD

**Issue by kevin-hirsch** [andreamazz/AMPopTip#30]
Hi @andreamazz, thank you for your super `AMPopTip`! :)

What do you think of adding a property like `arrowRadius` to have a rounded arrow?
I would like it very much! Something like this:

![screen shot 2015-05-05 at 13 49 02](https://cloud.githubusercontent.com/assets/2794684/7471975/bd40945c-f32d-11e4-8212-5a167f280f4a.png)

**Comment by andreamazz** [comment]
Hi @kevin-hirsch 
Yeah, I guess that I should be able to add it fairly quickly, I'll take a look at it in the next few days.

**Comment by kevin-hirsch** [comment]
Thank you very much! :+1:

**Comment by andreamazz** [comment]
> add it fairly quickly

Yeah, I was wrong. I'm having a bit of troubles implementing this. :sweat_smile:

**Comment by kevin-hirsch** [comment]
No worries ;)

**Comment by andreamazz** [comment]
Any idea (or PR) is welcome. Since the arrow is drawn point by point, adding a rounded tip requires some math: the offset of the starting and ending point of the straight lines, and the starting and ending angle of the arc that connects the two straight lines.

**Comment by kevin-hirsch** [comment]
Yeah I see the difficulty here ^^

Maybe you can try this: https://www.bignerdranch.com/blog/core-graphics-part-three-lines/#join-the-dark-side
```objc
enum CGLineJoin {
    kCGLineJoinMiter       // default
    kCGLineJoinRound
    kCGLineJoinBevel
}
```
![cg3-joinstyles](https://cloud.githubusercontent.com/assets/2794684/7591206/bc8e14ae-f8cc-11e4-8e72-75202191e1a8.png)

**Comment by andreamazz** [comment]
I'm using `UIBezierPath`s

**Comment by kevin-hirsch** [comment]
Right, forget my post above then ;)
I will see by my side what can be done but I will not have much time before WWDC 2015 ;)

**Comment by dylangattey** [comment]
Check this out? Not sure how much work this will be https://stackoverflow.com/questions/20442203/uibezierpath-triangle-with-rounded-edges

**Comment by andreamazz** [comment]
There's a bit of tinkering to do, but it certainly is doable.

**Comment by oleghnidets** [comment]
Hi,
Any updates?

**Comment by rserentill** [comment]
Hi, I just created a pull request (#157) with this feature. You can set the property arrowRadius (CGFloat) to set the arrow's corner radius.
