### ISSUE TITLE
Arrow size not correct when switching from left / right to up / down

### ISSUE THREAD

**Issue by kevin-hirsch** [andreamazz/AMPopTip#32]
Hello again @andreamazz,

I noticed a bug. If I set the arrowSize this way:

```objc
[AMPopTip appearance].arrowSize = CGSizeMake(10.0f, 18.0f);
```

It is showing correctly with right / left directions:
![img_2162](https://cloud.githubusercontent.com/assets/2794684/7478268/e6b62352-f359-11e4-8e39-440012fd041f.PNG)

But it reverse the values for up / down directions:
![img_2163](https://cloud.githubusercontent.com/assets/2794684/7478277/f37e90e2-f359-11e4-9124-f6ecd3d28a2d.PNG)

Can you look at this please?
Thank you :+1:

**Comment by andreamazz** [comment]
Sure, I'll check this out and let you know.

**Comment by andreamazz** [comment]
I don't know.... I'm torn. Which one is the correct one? :smile: 
In a kind of way they both are, width and height are a matter of perspective.

**Comment by andreamazz** [comment]
Ok, I made up my mind. Checkout commit 332421a and let me know. I considered the height the vertical position when the direction is top/bottom, and the horizontal position in the left/right.

**Comment by kevin-hirsch** [comment]
Thank you very much!
It seems great :)

Maybe just a small mistake (matter of perspective) in commit 332421a in `AMViewController` you wrote:
```objc
[AMPopTip appearance].arrowSize = CGSizeMake(10.0f, 18.0f);
```
Which shows this:
![wrong](https://cloud.githubusercontent.com/assets/2794684/7554594/4356e650-f72e-11e4-8c0e-729e64a3d405.png)

Instead of:
```objc
[AMPopTip appearance].arrowSize = CGSizeMake(18.0f, 10.0f);
```

which shows this:
![right](https://cloud.githubusercontent.com/assets/2794684/7554596/56467dc0-f72e-11e4-9ed6-3d9003fa6b8c.png)


PS: :+1:

**Comment by andreamazz** [comment]
I was toying around with the values, I should remove it :)

:+1:

**Comment by kevin-hirsch** [comment]
Okay! :)
