### ISSUE TITLE
Bounce doesn't work in Swift

### ISSUE THREAD

**Issue by samuelbeek** [andreamazz/AMPopTip#34]
I've can use all PopTip functionality  like this:                 

    self.tooltip.showText(self.pocketText, direction: AMPopTipDirection.Up, maxWidth: 260, inView: self.view, fromFrame:self.navigationBar.frame)
                    self.tooltip.popoverColor = greenColor

but somehow it is not possible for me to set bounce like this: 

     self.tooltip.bounce = true

What am I doing wrong? 
Thanks in advance :)

**Comment by andreamazz** [comment]
Hi @samuelbeek 
`bounce` is a function, not a property (there's just a readonly property, `shouldBounce` )
```swift
self.tooltip.bounce()
```

**Comment by andreamazz** [comment]
Sorry, my bad, bounce is indeed a property, not just a readonly getter. I'm guessing you are gettign this through cocoapods, in that case the code is not the latest. I'll push the new version right away.

**Comment by andreamazz** [comment]
Done.
