### ISSUE TITLE
Having problems using with swift

### ISSUE THREAD

**Issue by individual11** [andreamazz/AMPopTip#35]
Dropped AMProTip folder in and setup bridge header, no issues. Added this code

```Swift
var popTip: AMPopTip = AMPopTip()
popTip.showText("This is a test", direction: AMPopTipDirection.Up, maxWidth: 40, inView: self.view, fromFrame: CGRect(x: 0, y: 0, width: 40, height: 20))
```

getting this error on compile
```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_AMPopTip", referenced from:
      __TMaCSo8AMPopTip in DetailViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by andreamazz** [comment]
It's hardly an issue of this lib, anyway, I'll try and replicate your setup and let you know, maybe I can help.

**Comment by andreamazz** [comment]
Yep, works fine by copying the files and importing them in the bridging header. 
Maybe you did not add AMPopTip.m to your target? 
Checkout this sample setup: http://d.pr/f/1b3o6

Also, I strongly recommend cocoapods as a general rule when importing third party libs.

**Comment by liltimtim** [comment]
Hello Andrea, I'm using cocoapoded version and I'm getting the same issues.  I have "use_frameworks!" included in the cocoa pod and I have also tried importing the .h file "AMPopTip.h" into my bridging header.  Xcode doesn't complain about your header but complains about the architecture.

**Comment by andreamazz** [comment]
You don't need to include the header in the bridging header if you use `use_frameworks!`. 
Just add the pod, and import it. I'm using this lib in several swift projects with no issues, here's a simple project that includes it with CocoaPods:
http://d.pr/f/pBui

**Comment by liltimtim** [comment]
As previously stated in my comment above, I have also TRIED both methods, including the headers in the bridge file and not including them however I'm still getting the same issue. 

Also note that some pod files still require you to include headers inside your bridge file for example the Google pod for analytics and Fabric also requires you to include regardless if you have "use_frameworks" or not especially in projects that have mixed code (objectiveC and Swift) 

My next step that I will try is using an older version.
