### ISSUE TITLE
Not Dimissable

### ISSUE THREAD

**Issue by mawhtin** [andreamazz/AMPopTip#39]
Hi @andreamazz 

When I add an ActionAnimation, I have to tap it a many times super fast to get it to randomly dismiss.

However, if I remove the ActionAnimation it dismisses on first tap.

**Comment by mawhtin** [comment]
Here's my view hierarchy inspector. Nothing is blocking it either as expected since taking off actionAnimation allows it to be dismissable.

![screen shot 2015-05-28 at 1 42 50 pm](https://cloud.githubusercontent.com/assets/2721699/7870638/8cf6c93c-053f-11e5-8cf8-29a6fcd19ca4.png)
![screen shot 2015-05-28 at 1 43 53 pm](https://cloud.githubusercontent.com/assets/2721699/7870651/9d720ca4-053f-11e5-9413-f14446af85a0.png)

**Comment by mawhtin** [comment]
self.popTipOne = [AMPopTip popTip];
	self.popTipOne.popoverColor = [UIColor purpleColor];
	self.popTipOne.radius = 8;
	self.popTipOne.entranceAnimation = AMPopTipEntranceAnimationNone;
	self.popTipOne.actionAnimation = AMPopTipActionAnimationFloat;

	self.popTipOne.shouldDismissOnTap = YES;
	
[self.popTipOne showText:@"Chat and ask questions. How long's the wait? How's the crowd? Is the snow good?" direction:AMPopTipDirectionUp maxWidth:250 inView:self.view fromFrame:self.inputToolbar.frame];

**Comment by andreamazz** [comment]
Hi @mawhtin 
Yep, I see, if you tap the poptip it won't dismiss. It dismisses fine however if you tap outside the tip. I'll investigate further.

**Comment by mawhtin** [comment]
Thanks @andreamazz !

Really excited to have it be part of my app! It's awesome! :+1:

**Comment by andreamazz** [comment]
Glad to hear that! :)  
I forgot to set `UIViewAnimationOptionAllowUserInteraction` to the animation. The latest commit fixes it. :+1:

**Comment by andreamazz** [comment]
Pushed version `0.9.1` with the fix.

**Comment by mawhtin** [comment]
Works beautifully! Many thanks!
