### ISSUE TITLE
CPU 100%

### ISSUE THREAD

**Issue by bingxue314159** [andreamazz/AMPopTip#40]
tip.actionAnimation = AMPopTipActionAnimationBounce;
After pop or push the ViewControll,CPU rapidly rises to 100%
![snip20150609_3](https://cloud.githubusercontent.com/assets/10768058/8049152/a599f0e8-0e8d-11e5-8066-1e16022c2d9e.png)

**Comment by andreamazz** [comment]
Hi @bingxue314159 
I'll look into it as soon as possible, thanks for the feedback.

**Comment by andreamazz** [comment]
Ok, it should be fine now. I had to kill the animation on push, when you pop back you need to call
```objc
[popTip startActionAnimation];
```
