### ISSUE TITLE
No hiding animation since 0.9.6 build

### ISSUE THREAD

**Issue by xbitstream** [andreamazz/AMPopTip#41]

**Comment by andreamazz** [comment]
My bad. I fixed the issue in `0.9.8`

**Comment by dylangattey** [comment]
There's no pod for 0.9.8. Is that happening soon? Thanks!

**Comment by dylangattey** [comment]
Looks like the pod version is 0.9.8 in your podspec, but perhaps it hasn't been deployed to Cocoapods? I'd love that to be deployed at some point soon so I can use this fix! Thanks.

**Comment by andreamazz** [comment]
Sorry about that, I forgot to push the new podspec to trunk.
I'm having troubles doing so, though, I'll fix it first thing tomorrow. For now you can however use the `:head` option:
```
pod 'AMPopTip', :head
```
To pull the most recent changes.

**Comment by dylangattey** [comment]
Okay! sounds good. Thanks for creating this library. So useful!

**Comment by andreamazz** [comment]
Ok, I had to yank the 0.9.8 because it was failing remote validation even if the local lint was fine ¯\(°_o)/¯
You'll find the fix in version `0.9.9`

> Okay! sounds good. Thanks for creating this library. So useful!

:smile:
