### ISSUE TITLE
Add prebuilt binary

### ISSUE THREAD

**Issue by dasmer** [andreamazz/AMPopTip#45]
Adding a prebuilt binary to the tag will make it quicker for people using Carthage to use `AMPopTip`.
Just
```
carthage build --no-skip-current
carthage archive AMPopTip
```

and attach the created zip to the current tag :octocat:

**Comment by andreamazz** [comment]
>  make it quicker  

Modern life is too frenetic if you ask me. There's nothing better than launching a time consuming shell command and enjoying your life while it performs the desired actions. You have the time to sit, close your eyes, breath and ponder about the meaning of time, life and the human condition. If you are more like a go getter you can make sure to check some tasks off your TODO list, or, why not, keep in touch with the people you care about. Sometimes we lose touch with our human side, searching for the thrill of the moment, the split second of sheer enjoyment that we believe will make our life complete. And just as we think we reached it, it's too late.  

  

  
Just fooling around :grimacing: . That's a great tip :grimacing: I'll make sure to include the binaries in this and in the other libraries :+1:

**Comment by dasmer** [comment]
LOL! 

Thank you :octocat:

**Comment by andreamazz** [comment]
Done :+1:
