### ISSUE TITLE
Adding a header to a popover?

### ISSUE THREAD

**Issue by revantchandanala296** [andreamazz/AMPopTip#46]
Firstly, thank you for this amazing library which is really helpful. Is there a possibility of adding a header to the popover? Something like this:
![screen shot 2015-09-29 at 12 01 06 pm](https://cloud.githubusercontent.com/assets/4016752/10170157/d7f3b0d0-66a1-11e5-9edf-78fa1634a97f.png)

**Comment by andreamazz** [comment]
Hi @revantchandanala296 
The pop tip supports attributed text, so you can style the text with a bold header and plain text below.

**Comment by revantchandanala296** [comment]
Hi @andreamazz 
Thank you for your answer ! I was able to add header using the attributed text method, but I was not able to add padding between the header and the text. If I give a line return ("\n") , that adds way more space than needed, how to go about this?

**Comment by andreamazz** [comment]
Well... it's a bit hacky, but you can set a smaller font for the `\n` :grimacing:

**Comment by revantchandanala296** [comment]
yeah initially I did that, but I want the header and text should be of same
size and header should be bold

Revant Chandanala
-------------
Developer

135 Fifth Avenue, Third Floor, New York, NY 10010
Tel: 212-729-1544 x412  |  Mobile: 609-575-1465

**Comment by andreamazz** [comment]
You can change the font for just the `\n` despite the size of the other two strings

**Comment by andreamazz** [comment]
Closing this for now. Please refer to #52
