### ISSUE TITLE
Strange flashing behavior

### ISSUE THREAD

**Issue by joshhaug** [andreamazz/AMPopTip#48]
This is an EXCELLENT library.  It's exactly what I needed.
Quick issue: when rapidly adding/removing pops from my view, I'll get weird flashing above the point.  Is this an animation issue?  Forgive my ignorance, I'm a relatively new developer :) 

Keep up the good work!

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/3131141/10351241/47ef30ba-6cfd-11e5-90ce-30e506568455.gif)

**Comment by andreamazz** [comment]
Hi @joshhaug 
First of all, thanks! 
Yes, that's a glitch of the dismiss animation that I've been meaning to fix for a while. I hope to get some time to work on it soon, in the meantime you can try a different exit animation. 
I'll keep you posted

**Comment by joshhaug** [comment]
Excellent! Thank you!

**Comment by andreamazz** [comment]
Hi @joshhaug 
Sorry it took so long. I made some changes to restrict a bit the poptip state. Can you test again with your code?

**Comment by joshhaug** [comment]
Hi @andreamazz have you pushed these changes to the cocoapods repo? Tried updating from there with no success.

**Comment by andreamazz** [comment]
Not yet, I wanted to make sure they are working. Use the `:head` option to get the latest commit:
```
pod 'AMPopTip', :head
```

**Comment by joshhaug** [comment]
Great, will try it out now.

**Comment by lionel-alves** [comment]
Hi @andreamazz, @joshhaug,
Master doesn't build for me, fixed it here https://github.com/andreamazz/AMPopTip/pull/49, curious to know if it works for you though.

**Comment by NorbertSzydlowski** [comment]
Hide don't work when second Pop is showing with "Head:"

**Comment by andreamazz** [comment]
It works correctly on the sample project. Can you provide the code you are running?

**Comment by joshhaug** [comment]
It builds for me, but there's a new bug -- when added too quickly in succession, they won't disappear!
![friend](https://cloud.githubusercontent.com/assets/3131141/10829981/7a641c6a-7e3a-11e5-891c-94b20fe4d145.gif)
 Thanks for all your hard work @andreamazz

**Comment by andreamazz** [comment]
I'm guessing you are using a new poptip per point, calling hide on the others. Doing this in quick succession causes `hide` to be called before the poptip is completely shown. That's what was causing the flashing behaviour. To prevent that I forced the tip to hide only when completely shown. It's not a great, that's for sure, I hope to have a better fix this weekend. In the meantime you can try to reuse the same poptip, without hiding the previous one, but just calling `showText` again (this should just move the frame).

**Comment by joshhaug** [comment]
Ah! Perfect! Thank you :+1:

**Comment by andreamazz** [comment]
Hi @joshhaug 
I know this is awfully late, but since the latest version you can call showText multiple times over the same poptip. This might fix the issue.

**Comment by chetan-duke** [comment]
I love the forced! :D
