### ISSUE TITLE
Rebuild Binary with the latest version of Carthage

### ISSUE THREAD

**Issue by dasmer** [andreamazz/AMPopTip#50]
Newer versions of Carthage require dSYMs to be uploaded with the build. Since the binary was build with an older version of Carthage, it is missing the require dSYM

**Comment by dasmer** [comment]
In other words just

Update Carthage
```
carthage build --no-skip-current
carthage AMPopTip
```

and replace the release's binary :smile: 

Thanks @andreamazz

**Comment by andreamazz** [comment]
Done :+1:

**Comment by dasmer** [comment]
thank you!
