### ISSUE TITLE
it can't use in UITableViewController

### ISSUE THREAD

**Issue by utfqvfhpyygy** [andreamazz/AMPopTip#51]
it can't use in UITableViewController

**Comment by andreamazz** [comment]
It can be used without issues. 
Care to explain your issue besides the one liner?

**Comment by utfqvfhpyygy** [comment]
#import <UIKit/UIKit.h>

@interface NewMyTableViewController : UITableViewController

@end
==================

- (void)viewDidLoad {
    [super viewDidLoad];
    
    [self.chageRoleButton addTarget:self action:@selector(gotoChageRole) forControlEvents:UIControlEventTouchUpInside];
    
self.popTip = [AMPopTip popTip];
[self.popTip showText:@"test" direction:AMPopTipDirectionUp maxWidth:200 inView:self.view fromFrame:self.chageRoleButton.frame];
}


it is no happend.
i can't check the problem

**Comment by utfqvfhpyygy** [comment]
i use in uitablecontroller   that can't show the tips

**Comment by andreamazz** [comment]
Yeah, I need more than a piece of code that I can't run. 
Anyway, the type of the controller makes no difference, here's a small sample with a table view controller:
http://d.pr/f/22YF  

My first guess is that the frame of `changeRoleButton` pushes the view off the screen. Also, if the frame is inside a cell, consider the contentOffset of your table when providing the frame. Use the view hierarchy inspector to figure out where the popTip is displayed, or post some code that I can actually run.
