### ISSUE TITLE
can i set a custom view on the popview?

### ISSUE THREAD

**Issue by zhangjiajia** [andreamazz/AMPopTip#52]
i want to know ,how can i set a custom view on the popview? only text avaliable?

**Comment by andreamazz** [comment]
Yeah, as of right now only text is available. Supporting a custom view should be rather easy though, I'll add this to the future releases.

**Comment by andreamazz** [comment]
Done, checkout commit da2e03b. 
There's a new method to show a custom view:
```objc
- (void)showCustomView:(UIView *)customView direction:(AMPopTipDirection)direction inView:(UIView *)view fromFrame:(CGRect)frame duration:(NSTimeInterval)interval;
```

**Comment by zhangjiajia** [comment]
good! Thank you very much!

**Comment by OrchidVC** [comment]
Error display on sample:
 1. click show poptip custom view on top-left button
 2. click show poptip text on others button
-> Image from custom view overlap to poptip text
See attach file
![simulator screen shot dec 14 2015 10 36 07 am](https://cloud.githubusercontent.com/assets/11327980/11772440/e07e1c70-a24e-11e5-9283-640cb1cdb531.png)

**Comment by andreamazz** [comment]
It should be already fixed in the latest release.
See https://github.com/andreamazz/AMPopTip/issues/56
