### ISSUE TITLE
Setting appearance properties crashes on iOS 7

### ISSUE THREAD

**Issue by 0xABC** [andreamazz/AMPopTip#54]
The following lines are causing crashes on my iPod running iOS 7:

		AMPopTip.appearance().shouldDismissOnTap = true
		AMPopTip.appearance().shouldDismissOnTapOutside = false

The crash says:

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** Illegal property type, c for appearance setter, _installAppearanceSwizzlesForSetter:'

**Comment by andreamazz** [comment]
Yeah those two properties are not part of the appearance proxy, you need to set them on the instance itself.
