### ISSUE TITLE
Custom view don't removed from tooltip view.

### ISSUE THREAD

**Issue by RavenEIA** [andreamazz/AMPopTip#56]
Tooltip with attributed text looks incorrect if it was shown with custom view before.
![simulator screen shot 07 dec 2015 11 15 38](https://cloud.githubusercontent.com/assets/7067128/11622112/e0d4c208-9cd3-11e5-9d2a-f51f3b716b51.png)

**Comment by andreamazz** [comment]
Good catch. 
Fixed in 05324f1
