### ISSUE TITLE
Nested Frames and UIStackView

### ISSUE THREAD

**Issue by cloud-tribal** [andreamazz/AMPopTip#57]
PopTips do not play nice in Nested Frames or in UIStackViews.

The arrow points to the inside of the frame at a position that is difficult to determine beforehand.

Any ideas?

**Comment by andreamazz** [comment]
Hi @cloud-tribal 
Can you provide a sample of the issue?

**Comment by cloud-tribal** [comment]
Hi Andrea,

First of all, awesome library, and thank you for making it.

I have learned, in the process of testing for ways to get AMPopTip to work in my app, that when you have a UIView that is nested within another UIView or a UIStackView, calling someView.frame is going to give you a CGRect whose coordinates' origin are based on the origin of the containing UIView.

It may be by design, but I realized that the frame required by PopTips is the absolute frame of the view relative to the app. I haven't done enough tests or read the source code to say for sure, but of the 20 nested/stacked view hierarchy variations I've tried, 'someView.frame' never works.

Correct me if I am wrong, but in my tests I have realized that for a nested/stacked UIView, the frame required by AMPopTip is actually:

            let newFrame = someView.convertRect(someView.frame, toView: nil)

If this is the case, I think it would definitely be worth mentioning in the Usage section, especially for beginners like me who have come to your library before having learned such concepts.

**Comment by andreamazz** [comment]
Hi @cloud-tribal 
Yes, you are right, you should convert the frame when using nested views. I see your point, I've added a note in the [readme](https://github.com/andreamazz/AMPopTip#coordinate-system).  
Thank you for the precious feedback.
