### ISSUE TITLE
don't support custom view with AutoLayout?

### ISSUE THREAD

**Issue by LiweiDong** [andreamazz/AMPopTip#59]

**Comment by andreamazz** [comment]
Please provide more context...

**Comment by erdemPinch** [comment]
Hi, 
I have also a problem with a custom view. When calling `showCustomView`, nothing is showed up on the screen. I used AutoLayout for the custom view, this why a post a message here.

I am trying to show an PopTip with custom view after selecting a cell of a UICollectionView, but nothing is showed up.
What information do you need for debugging ?
(Sorry for my bad english.)

**Comment by andreamazz** [comment]
By nothing you mean the content or the whole popTip? If you don't see the bubble it may be due to wrong coordinates passed in the `fromFrame` param.  
Can you post some of the code you are using?

**Comment by erdemPinch** [comment]
Here the code i use:
`let convertRect = cell.convertRect(cell.bounds, toView: calendar)`
`popTip.showCustomView(dayPeriodView, direction: .Down, inView: calendar, fromFrame: convertRect)`

When calling `showText` like this (for testing)
 `popTip.showText("Test", direction: .Down, maxWidth: 100, inView: calendar, fromFrame: convertRect)`
everyThing is showing fine and the popTip is at the right place.

**Comment by erdemPinch** [comment]
Sorry i forgot to say:
By Nothing, i mean the whole popTip is not showed up.

**Comment by andreamazz** [comment]
Can you log the popTip's frame once you presented it?

**Comment by erdemPinch** [comment]
Yes, it has a frame of (0,0,0,0) 
I try to place a frame (for test) like this
`popTip.frame = dayPeriodView.frame`
but it didn't work as well.

**Comment by andreamazz** [comment]
Yeah, it's probably autolayout then. I reckon it's guessing the custom view's frame before autolayout did his thing.

**Comment by erdemPinch** [comment]
Ok then, Do you have a quick fix for now or something else ?

**Comment by andreamazz** [comment]
Checkout latest commit. It's a wild guess, but who dares wins.

**Comment by erdemPinch** [comment]
Ok thanks, I will try it now.

**Comment by erdemPinch** [comment]
Sorry, but it didn't work.

**Comment by andreamazz** [comment]
Can you reproduce the issue in the sample project by any chance?

**Comment by erdemPinch** [comment]
yes I can try, i will try it now.

**Comment by erdemPinch** [comment]
So I can reproduce it by adding my custom view in your sample project.
Dumb question: Can I give it to you like that? if yes, how do we proceed ?

**Comment by andreamazz** [comment]
Dunno, if you want you can send it at andrea@fancypixel.it

**Comment by erdemPinch** [comment]
I just send you the popTipDemo modified :)

**Comment by erdemPinch** [comment]
Any news on that bug ? :)

**Comment by andreamazz** [comment]
Yeah, I figured out what's breaking stuff (layoutSubviews gets convulsively called), but I still need to figure out how to stop the madness. In the meantime you can ditch autolayout for that view (there's not much reason to use it for a simple view that does not need to scale)

**Comment by erdemPinch** [comment]
Ok thanks ! 
let me now if you find a solution :)

**Comment by songjisj** [comment]
set poptip.translatesAutoresizingMaskIntoConstraints = false works for me

**Comment by andreamazz** [comment]
Hi all. Sorry for the delay. Can you test again the issue now that #66 is merged in?

**Comment by andreamazz** [comment]
This should be fixed on master. Reopen if you need further assistance.
