### ISSUE TITLE
shouldDismissOnTapOutside doesn't work if you tap on a button?

### ISSUE THREAD

**Issue by jalbano** [andreamazz/AMPopTip#60]
I have a tip displayed that explains they need to tap on a button to do something. If the user then actually taps the button (and not the tip), the tip doesn't get dismissed. Is there any way to get this behavior or is this a bug?

**Comment by andreamazz** [comment]
The gesture recognizer is attached to the containing view, this doesn't cover the button. You might want to programmatically hide the poptip in the action associated to the button.

**Comment by andreamazz** [comment]
Closing this, let me know if you need further assistance.
