### ISSUE TITLE
AMPopTip Doesn't work with XIB created CustomView set for this PopTip, All App hangs

### ISSUE THREAD

**Issue by vickyrappier** [andreamazz/AMPopTip#63]
Hello I am building the AMPopTip with this code as mentioned , but the UI hangs if I use the XIB created custom view.

@property (nonatomic, strong) AMPopTip *popTip1;
@property (nonatomic, strong) CLInfoPopUpView *popUpView; //My view

//Initialised tried using local in button tape or in View did load as well :
CLInfoPopUpView * popView  = [[[NSBundle mainBundle] loadNibNamed:@"CLInfoPopUpView" owner:self options:nil] lastObject];

    self.popTip1 = [AMPopTip popTip];
    self.popTip1.shouldDismissOnTap = YES;
    self.popTip1.edgeMargin = 0;
    self.popTip1.offset = 2;
    self.popTip1.edgeInsets = UIEdgeInsetsMake(0, 0, 0, 0);
    [self.popTip1 setBackgroundColor:[UIColor grayColor]];
    [self.popTip1 setPopoverColor:[UIColor grayColor]];

The Button function of tap show this.

if ([self.popTip1 isVisible]) {
        [self.popTip1 hide];
        
        self.popTip1 = [AMPopTip popTip];

        return;
    }
        [self.popTip1 showCustomView:popView direction:AMPopTipDirectionDown inView:self.view fromFrame:cell.infoBtn.frame];

Tool tip comes first time but later app hang no operations happening.  Similarly if I try using the UIview alloc init method to make the custom view as u show in Demo it work , can you help why this is happening.

**Comment by Raymond26** [comment]
I encountered a similar issue.  It would happen if I had a textview/textfield inside my custom view (and i imagine it would happen with other elements), and autolayout would make a call to viewDidLayoutSubviews().  If I had nothing in my custom UIView, then this wouldn't occur.  I noticed in the Instruments profiler that any layoutSubviews() related code was causing my app to hang, and this was not isolated to this specific popover library.  I ultimately decided to not go with showCustomView, and just customized my popover via settings.

**Comment by andreamazz** [comment]
Hi all. 
Sorry for the delay in my response. Any news on this? Did @Raymond26 solution suffice?

**Comment by yasirmturk** [comment]
same here, it seems like AutoLayout enabled xib issue

**Comment by yasirmturk** [comment]
it gets into unlimited loop calling this method

`- (void)layoutSubviews {
    [super layoutSubviews];
    [self setup];
}`

**Comment by jaroslavas** [comment]
I have the same problem. Do you plan a fix for this anytime soon?

**Comment by andreamazz** [comment]
Can you provide a sample project showing the issue?

**Comment by andreamazz** [comment]
Checkout commit 171f0a8
It's a blind fix though, let me know

**Comment by jaroslavas** [comment]
Looks like it's ok now. Doesn't crash :)

**Comment by andreamazz** [comment]
Great 👍 
Release `1.0.1`
