### ISSUE TITLE
Update description under title

### ISSUE THREAD

**Issue by lfarah** [andreamazz/AMPopTip#64]
<img width="295" alt="screen shot 2016-03-10 at 10 26 18 pm" src="https://cloud.githubusercontent.com/assets/6511079/13694955/2905e8ce-e70f-11e5-85dc-16fe5f074bd7.png">
I think that this would be better and more informative:
> Animated popover that pops out of a frame

**Comment by andreamazz** [comment]
Good point. I made the change :+1: 
Thanks @lfarah
