### ISSUE TITLE
PopTip Pointing at the wrong position

### ISSUE THREAD

**Issue by FirasAwad** [andreamazz/AMPopTip#68]
In ScrollView if you scroll down or up and trigger the PopTip it will point faraway from the frame it was supposed to point on. every time you change the position of the view the PopTip will point on different spot.
Thanks in advance

**Comment by andreamazz** [comment]
Hi @FirasAwad 
When presenting in a scrollview you need to account for the scrollView's content offset.

**Comment by FirasAwad** [comment]
Thank you so much for your reply and for the lovely library :)

**Comment by andreamazz** [comment]
Happy to help 😄 
Closing this, fell free to reopen if you need further help.

**Comment by MincDev** [comment]
For anyone else who needs a clear explanation, show it as follows:

`self.popTip?.showText("Some Text", direction: AMPopTipDirection.down, maxWidth: 200, in: self.scrollView, fromFrame: self.someview.frame)` <-- Notice that the in: field says self.scrollView and not self.view. This will make your tooltip move with its target.

**Comment by Smiller193** [comment]
this did not work for me

**Comment by MincDev** [comment]
@Smiller193, did you try what I posted? If you can post an example I can try and help you

**Comment by MincDev** [comment]
@bosong Can you explain a little more? fromFrame.size does not have a property called "y"
