### ISSUE TITLE
Can't change position of currently displayed tip

### ISSUE THREAD

**Issue by jaroslavas** [andreamazz/AMPopTip#71]
I'm showing tooltip over a collection view cell that was pressed last. If I just call `showText:` on every click, tolltip opens only after the first click and does nothing on the next clicks. It would be good, if tooltip would update it's position and text when `showtext:` is called on the already visible tooltip.

PS. For the moment I made two tooltip objects and hide one and show second one on click, but that doesn't seem right.

**Comment by cerupcat** [comment]
I'm trying to do the same thing. Not sure what the best solution is.

**Comment by andreamazz** [comment]
Done. Please checkout the master and let me know if it's working as expected so I'll push a release.

**Comment by jaroslavas** [comment]
It works 👍

**Comment by andreamazz** [comment]
Ace 👍 
Release `1.0.1`

**Comment by jaroslavas** [comment]
Thanks for fast response!
