### ISSUE TITLE
dismissHandler not called when the app goes to background and  become foreground again 

### ISSUE THREAD

**Issue by lazybetrayer** [andreamazz/AMPopTip#72]
When the app goes to background with poptip (with a duration) showing and  become foreground again, the poptip dismisses but the dismissHandler it not called. And isVisible is always true

**Comment by andreamazz** [comment]
> When the app goes to background with poptip (with a duration)

Hi @lazybetrayer 
What do you mean by "with a duration"?

**Comment by lazybetrayer** [comment]
Hi @andreamazz 
Sorry for my bad English. I mean a poptip that automatically dismiss after a specific duration.

**Comment by andreamazz** [comment]
Gotcha. I'm guessing that the animation block is not called, since it's in background, so neither does the completion. I'll fix it as soon as possible.

**Comment by andreamazz** [comment]
Ok, the latest commit should do the trick. Let me know if it works for you, so I can push a new release.

**Comment by lazybetrayer** [comment]
Hi @andreamazz 
Thanks for your quick fix. It works for me.

**Comment by andreamazz** [comment]
👍 
Released `1.0.2`
