### ISSUE TITLE
Bubble Padding X position

### ISSUE THREAD

**Issue by JaimeYesidLeonParada** [andreamazz/AMPopTip#74]
It is possible to add a padding for the Bubble, position X? In some cases it is necessary move the bubble but not the arrow, for example:

[http://www.dreamtemplate.com/dreamcodes/documentation/dc_images/dc-tooltips.jpg](url) 
![dc-tooltips](https://cloud.githubusercontent.com/assets/4239636/15433164/be2403d4-1e76-11e6-8dfe-fc71522a4c21.jpg)

I tested into a fork and looks good.

Thanks

**Comment by andreamazz** [comment]
Hi @JaimeYesidLeonParada 
Which fork did you use?

**Comment by JaimeYesidLeonParada** [comment]
Hi @andreamazz ,
I use this personal fork [https://github.com/JaimeYesidLeonParada/AMPopTip]. 
I am working in this moment using the pod from path.

The idea is easy, add a horizontal offset, if the offset value is positive the bubble needs to move right side and if the  value offset is negative the bubble needs to move left side.

I will appreciate very much whether you can add this functionality into AMPoptip.

**Comment by JaimeYesidLeonParada** [comment]
@andreamazz If do you want I can do a PR with this new functionality.

**Comment by andreamazz** [comment]
Hi, yeah I would appreciate that :)
Can you call the property `horizontalOffset` instead of `offsetHorizontal`? Thanks 👍

**Comment by JaimeYesidLeonParada** [comment]
@andreamazz excellent. I'll keep you posted.

**Comment by JaimeYesidLeonParada** [comment]
@andreamazz I create the PR https://github.com/andreamazz/AMPopTip/pull/75. I call the property as **bubbleOffset**.

**Comment by jpv123** [comment]
Amazing idea! I would love to use this, @andreamazz can you approve and release a new version with this today? It would be an incredible improvement for all of us that use your framework :D

**Comment by JaimeYesidLeonParada** [comment]
Hi @andreamazz , I waiting for the approval to the PR, after this I would like to implement another feature that I had seen in another apps.

**Comment by andreamazz** [comment]
This should be solved now. Closing it, feel free to reopen if you need further assistance. 👍

**Comment by nevinjethmalani** [comment]
Can you add this to the docs? This is really helpful but I had to come and check the issues page to see if someone else was having this problem and only then did I see that this feature is available. Would have been great to have it in the readme. Great tool by the way!

**Comment by andreamazz** [comment]
Done 👍

**Comment by CoderTian** [comment]
I Set this property, But The entire view moves, including arrows？
```
        cell.showTipBlock = { [weak self] (viewModel, label) in
            let energyTipView = MyTeamEnergyContributeView(frame: CGRect(x: 0, y: 0, width: 115, height: 100))
            energyTipView.bindViewModel(viewModel)
            
            guard let _self = self else { return }
            let newFrame = cell.convert(label.frame, to: _self.tableView)
            _self.popTip.edgeMargin = 0
            _self.popTip.bubbleOffset = CGFloat(-30)
            
            _self.popTip.show(customView: energyTipView, direction: .down, in: _self.tableView, from: newFrame)
        }
```

**Comment by andreamazz** [comment]
@CoderTian 
Yes, the `offset` property moves the whole poptip from the origin, arrow included. 

(BTW, you can use backticks if you don't want to prefix `self` with an underscore:
```
guard let `self` = self else { return }
self.doSomething()
```

**Comment by CoderTian** [comment]
Yes thanks！ 
 Is it necessary to do so？when the frame origin change, the arrowPosition also change? this code work good, The arrow will at the correct position！
```Swift
    frame.origin.x += bubbleOffset
    arrowPosition.x -= bubbleOffset
    frame.size = CGSize(width: frame.width + borderWidth * 2, height: frame.height + borderWidth * 2)

    return (frame, arrowPosition)
```
