### ISSUE TITLE
PopTip appearing under UINavigationBar

### ISSUE THREAD

**Issue by acegreen** [andreamazz/AMPopTip#76]
Seems to be happing after updating to the latest version. I have a poptip appear from one of the UIBarButtonItem. Well I hardcode the y = -10 as taping the frame of a UIBarButtonItem is frowned upon. Previously the it behaved as expected and the poptip would appear from the item and above the navigation bar. Now it appears under as if the UINavigationBar is higher on the z axis. 

Demo:
http://recordit.co/TyR1E2Sjgn

**Comment by andreamazz** [comment]
Hi @acegreen 
Sorry it took me a while to reply. Which version were you using before?
In which view do you attach the poptip?

**Comment by animeshp** [comment]
I'm also facing the same behavior. I'm using AMPopTip v3.5.0 on iPhone X (iOS 12).

I've to hardcode `y = y + 10` in the fromFrame before showing pop tip.
