### ISSUE TITLE
Stops responding to `hide` if a view controller is presented when tip is visible

### ISSUE THREAD

**Issue by n00bProgrammer** [andreamazz/AMPopTip#80]
Let's say I have a view in which I have shown a `popTip`.
If I present a view controller on this view, and come back to it after dismissing that view controller, the `popTip` instance stops responding to the `hide` call.

Upon a little investigation, I found out the `isVisible` property becomes `NO` once I present the view controller in question here. Since `isVisible` is a `readonly` property, there is no way for me re-toggle it to `YES` in `viewWillAppear:` of the parent view of the `popTip`.

To handle this, at my end, I think I should take the Category Implementation route, or is there another way to tackle this?

**Comment by andreamazz** [comment]
Hi @n00bProgrammer 
Check out the latest commit for a fix. Let me know if it works so I can push a new version.

**Comment by n00bProgrammer** [comment]
@andreamazz Yep. Works as intended now. 👍🏻

**Comment by andreamazz** [comment]
Cool beans. Release 1.1.1
