### ISSUE TITLE
AMPopTipActionAnimationBounce Dismiss Artifacts

### ISSUE THREAD

**Issue by deRonbrown** [andreamazz/AMPopTip#84]
As shown in the animated GIF below, if the popover is dismissed at a particular moment during the bounce animation, a large artifact will flash over the part of the screen in the direction of the animation. After some investigation this issue only appears if you dismiss it _just_ before the start of the animation.

![animation](https://cloud.githubusercontent.com/assets/474564/17139184/5eeec8d4-5311-11e6-8c5e-5426a6c98c89.gif)

Looking through the animation code, unlike `AMPopTipActionAnimationPulse` and `AMPopTipActionAnimationFloat` which are implemented using `UIViewAnimationOptionRepeat` and `UIViewAnimationOptionReverse` options, `AMPopTipActionAnimationBounce` is animated using 2 separate and repeating blocks which are stopped using the `shouldBounce` property. I haven't been able to produce this issue for the other animation types, so maybe this difference in implementation creates the issue.

I'll dive in and submit a PR if I can get a fix, but I just wanted to put this on your radar.

**Comment by andreamazz** [comment]
Hi @deRonbrown 
Yeah, this is a known issue, see #48 
I have no idea why it does that, I tried to fix this for a while, I hope you have better luck 😄

**Comment by deRonbrown** [comment]
@andreamazz, ok. I didn't see #48. I switched over to using `AMPopTipActionAnimationFloat` in the interim, but I'll take some more looks over the next few days or so.

**Comment by burakkilic** [comment]
+1

**Comment by andreamazz** [comment]
It took me a year, but it should be fixed now. This was beyond tricky.
