### ISSUE TITLE
Poptip does not hide on tap

### ISSUE THREAD

**Issue by rajeevcbhatia** [andreamazz/AMPopTip#85]
I am using the AMPoptip to show a message to my user as follows:-

``` swift
popTipForNewStoriesCount = AMPopTip()

let lblNewMessagesCount = UILabel()
lblNewMessagesCount.numberOfLines = 0
lblNewMessagesCount.textColor = UIColor.whiteColor()
lblNewMessagesCount.textAlignment = .Center
lblNewMessagesCount.text = "my text"
lblNewMessagesCount.sizeToFit()
lblNewMessagesCount.adjustsFontSizeToFitWidth = true

popTipForNewStoriesCount?.shouldDismissOnTapOutside = false

popTipForNewStoriesCount?.showCustomView(lblNewMessagesCount, direction: AMPopTipDirection.Down, inView: self.view, fromFrame: CGRectMake(barButtonItemFrame.origin.x, 3, barButtonItemFrame.width, 0))

timerForNewStoriesPopTip = NSTimer.scheduledTimerWithTimeInterval(10.0, target: self, selector: #selector(MainViewController.timerForNewStoriesPopTipTick), userInfo: nil, repeats: false)

popTipForNewStoriesCount?.tapHandler = 
{
       self.hideNewStoriesPopTip()
}
```

hideNewStoriesPopTip is defined as:-

``` swift
func hideNewStoriesPopTip()
{
    popTipForNewStoriesCount?.hide()
    popTipForNewStoriesCount = nil

    timerForNewStoriesPopTip?.invalidate()
    timerForNewStoriesPopTip = nil
}
```

I am setting it to nil since I am using the "== nil" check to confirm if it is on the screen or not. In some cases, the poptip does not go away on tap. This is a very random issue and I cannot find the cause for that. Is there some problem with my implementation?

Another possible cause is that this sometimes replicates when the app is opened after a long time. Is it related to the suspended state of the app?

Thanks

**Comment by andreamazz** [comment]
Hey @rajeevcbhatia 
You can achieve the same effect by using the basic api:
```
popTipForNewStoriesCount?.shouldDismissOnTapOutside = false
popTipForNewStoriesCount?.shouldDismissOnTap = true
popTipForNewStoriesCount?.dismissHandler = {
  // ...
}

```
No need to add another gesture recognizer (that might be the issue).

**Comment by rajeevcbhatia** [comment]
Thanks @andreamazz . So in the tap handler I only need to stop the timer and set it to nil?

**Comment by andreamazz** [comment]
Yep.

**Comment by rajeevcbhatia** [comment]
Thanks Andrea, I'll try that solution and update here.

**Comment by rajeevcbhatia** [comment]
Hey @andreamazz . I tried an alternate approach by using the inbuilt timer and the isVisible flag instead of setting this to nil. The problem was that the isVisible flag was returning true sometimes when the popup was visible so just reverted to this implementation
