### ISSUE TITLE
Change text dynamically

### ISSUE THREAD

**Issue by oleghnidets** [andreamazz/AMPopTip#86]
Hi,

I want to update text of presented top tip, but I'm limited to use `-showAttributedText:` or `-showText:`. And every time when I use these methods I see the animation (looks not very nice when I'm tapping the text).
Is it possible to make some methods or public properties for such purpose?

Thanks in advance,
Oleg

**Comment by andreamazz** [comment]
Hi @oleghnidets 
The update of the text is not currently supported. 
I think it might be a welcome addition though, I'll work on it as soon as I can.

**Comment by andreamazz** [comment]
It only took me 8 months, but it's up on master.
