### ISSUE TITLE
Hiding even though a popTip is animating.

### ISSUE THREAD

**Issue by urosMihailovic** [andreamazz/AMPopTip#88]
Hey @andreamazz! I was wondering would it be ok to force hiding while a popTip is animating? I need this behavior in my project, since sometimes a user can dismiss a viewController while the tag is animating it's entrance, resulting in popTip dangling over the previous VC.

I taught I could achieve this by removing this first if statement in the hide method.
```
- (void)hide {
    if (self.isAnimating) {
        return;
    } 
   .
   .
   .
```

**Comment by andreamazz** [comment]
Hi @urosMihailovic 
You can probably achieve that effect by using no exit animation. (`AMPopTipExitAnimationNone`)

**Comment by urosMihailovic** [comment]
Unfortunately this didn't help. My issue is the entrance animation, and I need to have it. I've tried without the `return;` in `hide`, it's working. Hopefully it won't have some side effects.

**Comment by andreamazz** [comment]
I guess I can add a `hide(force:)` method.
Let me check.

**Comment by andreamazz** [comment]
Ok, checkout the current master version. You'll find `hideForced:` method. Pass true and the animation checked is skipped. If it works I'll pusha  new release.

**Comment by andreamazz** [comment]
Sorry, forgot to push, it's up now.

**Comment by andreamazz** [comment]
Closing this, let me know if you need further help.

**Comment by urosMihailovic** [comment]
Everything is working fine with the new `hideForced`. Thank you @andreamazz!
