### ISSUE TITLE
Tooltip height does not fit text height

### ISSUE THREAD

**Issue by carole-lavillonniere** [andreamazz/AMPopTip#89]
Since the update to the latest version (1.3.0), the tooltips height seems to be slightly off when using a custom font. The height is updated depending on the text but it does not fit all of the text. My current fix for this is to append a few extra line breaks to the text.

See screenshot. The text should be "Tap here to view your favourites."
The only property of the appearance that has been overwritten is the font.

<img width="184" alt="screenshot 2016-09-30 17 46 03" src="https://cloud.githubusercontent.com/assets/1684627/18997752/1dce8e30-8736-11e6-8c43-3f119238a5a4.png">

**Comment by andreamazz** [comment]
Hi @carole-lavillonniere 
Are you setting the font in the appearance proxy by any chance?
That was a bug and corrected in 1.2.0
From that version forward you need to set the custom font on the instance instead.
See #77

**Comment by carole-lavillonniere** [comment]
You are right, this fixes it. Thanks.

**Comment by andreamazz** [comment]
👍
