### ISSUE TITLE
PopTip width

### ISSUE THREAD

**Issue by acegreen** [andreamazz/AMPopTip#90]
Hey, 

This implementation used to work but now it cuts text off. Any idea whats causing this? Seems to be a recent issue

<img width="1147" alt="screen shot 2016-10-15 at 10 57 20 am" src="https://cloud.githubusercontent.com/assets/10794609/19410982/7bf4fa1c-92c6-11e6-965f-c5946b718ef9.png">

<img width="1193" alt="screen shot 2016-10-15 at 10 57 40 am" src="https://cloud.githubusercontent.com/assets/10794609/19410987/8135f0c6-92c6-11e6-8521-acb033062334.png">

** EDIT: **
- Simple String instead of NSLocalizedString doesn't make a difference
- using self.view instead of self.navigationController.view doesn't make a difference neither

**Comment by andreamazz** [comment]
Hi @acegreen. Please take a look at #89. 
Basically you need to set the custom font on the pop tip instance instead of the appearance proxy.

**Comment by acegreen** [comment]
@andreamazz I'll be damned. Is this a recent change in the library or something I did on my end (potentially during the Swift 3 migration)?

**Comment by acegreen** [comment]
[Resolved]

**Comment by andreamazz** [comment]
Recent change. It was a bug to begin with, since fonts don't work with the appearance proxy.

**Comment by acegreen** [comment]
Thanks for the swift response
