### ISSUE TITLE
Crash on tap

### ISSUE THREAD

**Issue by leolobato** [andreamazz/AMPopTip#91]
I'm currently using `AMPopTip` 0.9.13 on a project and updated to the latest version tagged (1.3.0).

Now the app crashes when the popover is tapped:

```
-[AMPopTip performExitAnimation:]: unrecognized selector sent to instance 0x7b79c090
```

`-performExitAnimation:` is called from the `-hide` method, but it is not declared anywhere.

**Comment by andreamazz** [comment]
Hey @leolobato 
Seems to be working fine in the sample app. `performExitAnimation` is declared and implemented in a class extension in `AMPopTip+Exit.h`
How are you importing the library in your app?

**Comment by andreamazz** [comment]
No response, I assume you fixed it. Feel free to reopen if needed.
