### ISSUE TITLE
Cannot convert to rect in nested view

### ISSUE THREAD

**Issue by burakkilic** [andreamazz/AMPopTip#93]
Hi;

I have a horizontal scrollview with UIImageViews and each has a tap recognizer attached.

When user taps an image, I want to show a PopTip over that image. The function is below.
    

    -(void)tapped:(id)sender{
        UITapGestureRecognizer* recognizer = (UITapGestureRecognizer*)sender;
        self.popTip = [AMPopTip popTip];
        UIWindow *window = [UIApplication sharedApplication].keyWindow;
        UIView* v = [window.subviews objectAtIndex:0];
        CGRect rect = [recognizer.view convertRect:recognizer.view.frame toView:nil];
        [self.popTip showText:@"I'm a popover popping over" direction:AMPopTipDirectionUp    maxWidth:200 inView:v fromFrame:rect];

    }

I carefully read the comment about convertToRect and tried many different ways, but I couldn't succeeded. The y coordinate is true. But the x is always increasing. Please check out the images below:

![screen shot 2016-11-16 at 17 28 35](https://cloud.githubusercontent.com/assets/123382/20351034/e3d58b58-ac19-11e6-8cbf-b1618f82ce73.png)
![screen shot 2016-11-16 at 17 28 27](https://cloud.githubusercontent.com/assets/123382/20351035/e3d8ae8c-ac19-11e6-84fd-6dfb689b108e.png)

What is the proper way to find the rect in such a case?

**Comment by andreamazz** [comment]
Hey @burakkilic 
Why are you referencing directly the window? Can't you just get the view's reference from the view controller?

**Comment by burakkilic** [comment]
Hi @andreamazz 

I changed my code to:

    CGRect rect = [recognizer.view convertRect:recognizer.view.frame toView:self.contentView];
    [self.popTip showText:@"Title" direction:AMPopTipDirectionUp maxWidth:200 inView:self.contentView fromFrame:rect];

This code is inside a subclass of UICollectionViewCell. Therefore I referenced its contentView. But that time, popover is displayed over collection view cell.

**Comment by andreamazz** [comment]
I'm not sure I follow. Can you provide a sample project showing the issue so I can try to fix it?

**Comment by burakkilic** [comment]
I solved my problem using:

    CGRect rect = [recognizer.view convertRect:recognizer.view.bounds toView:self.contentView];

When converting to view, rectangle should be bounds, not the frame. I don't know why but it worked.

**Comment by andreamazz** [comment]
Glad to hear that mate. 👍
