### ISSUE TITLE
swift 3

### ISSUE THREAD

**Issue by imanuelpardosi** [andreamazz/AMPopTip#94]
Is this work on swift 3?

**Comment by andreamazz** [comment]
Sure

**Comment by imanuelpardosi** [comment]
but I got more errors.
like:
Value of type 'AMPopTip' has no member 'detailTextSize'
Value of type 'AMPopTip' has no member 'contentTextSize'
Value of type 'AMPopTip' has no member 'headerTextSize'
and so on...

how to fix that?

**Comment by andreamazz** [comment]
Those are in fact no members of AMPopTip, who is trying to access those? Can you post some of the code you are using?
