### ISSUE TITLE
Memory Retains

### ISSUE THREAD

**Issue by SeanLintern** [andreamazz/AMPopTip#99]
Great library!

One thing i've noticed is that it retains self in some of the blocks meaning it would not dealloc, I have manually nil'ed it in my wrapper when I am done with it which fixes this but others may not have done so, other than that seems great :D

**Comment by andreamazz** [comment]
Hey @SeanLintern 
Thanks for the heads up. Can you also point out which one is retained?

**Comment by andreamazz** [comment]
Should be fixed now.

**Comment by SeanLintern** [comment]
Sorry I didnt see the reply, but thanks :D
